### ISSUE TITLE
Please restore support for Windows to WidevineCDM

### ISSUE THREAD

**Issue by PhantomNimbi** [jiahaog/nativefier#797] opened 2019-04-23 08:41 UTC
### Description

Please restore Windows support to WidevineCDM as a part of nativefier.

### Steps to reproduce issue

Basically, run any nativefier command on Windows to attempt to create a native app that uses DRM protection. It no longer works on Windows computers. Google Chrome's implementations keeps failing and the electron widvinecdm plugin is discontinued by the developer. He/She stated on the page though that anyone who wishes to take over the project can do so, they just need to contact him/her.  As it is, it's outdated and has no Windows support at all.

### Details

- Are you nativefying a *public* website? Yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? Yes
- Full nativefier command used to build your app: `nativefier --name "NETFLIX" "https://www.netflix.com/" --flash --widevine-cdm-path "C:\Program Files (x86)\Google\Chrome\Application\73.0.3683.103\WidevineCdm\_platform_specific\win_x64\widevinecdm.dll\" --widevine-cdm-version "4.10.1303.2"`

- Version of Nativefier (run `nativefier --version`): `v7.6.12`
- Version of node.js (run `node --version`): `v10.15.3`
- OS: `Windows 7 Ultimate x64`
- Error message / stack trace (if any):
![Untitled](https://user-images.githubusercontent.com/17615050/56566798-5d6dec80-6568-11e9-8c01-42aa8e9f9d2c.png)

<https://libraries.io/npm/electron-widevinecdm>

**Comment by mxdpeep** [comment] 2019-09-03 08:31
*this is impossible!*
Widevine is a commercial platform, needs a license for any browser project

**Comment by ronjouch** [comment] 2020-01-29 04:29
Closing as duplicate of https://github.com/jiahaog/nativefier/issues/435

**Closed by ronjouch** 2020-01-29 04:29 UTC
