### ISSUE TITLE
Cannot Play Audio, Convert Pocket Casts Web App to Native

### ISSUE THREAD

**Issue by Dreamcreate** [jiahaog/nativefier#134] opened 2016-02-15 19:28 UTC
I can't seem to get audio working from Pocket Casts website. Artwork does not load, and when clicking on any podcast, I get an error that playback is not possible. Any suggestions?

Edit:
<img width="554" alt="screen shot 2016-02-16 at 18 02 41" src="https://cloud.githubusercontent.com/assets/12797036/13082030/a69b8112-d4d7-11e5-9bc3-c54ee6b1d78e.png">

**Comment by wiederkehr** [comment] 2016-02-18 11:31
Hi @Dreamcreate, as far as I can see the problem you're describing is related to HTTPS. Pocket Casts (https://play.pocketcasts.com) is served over HTTPS while some of the podcasts and their assets are not. 

When you open the developer console, you will see this warning:
```
Mixed Content: The page at 'https://play.pocketcasts.com/web#/podcasts/new_releases' was loaded over HTTPS, but requested an insecure image 'http://discover.pocketcasts.com/discover/images/130/2f31dfb0-2249-0132-b5ae-5f4c86fd3263.jpg'.
```

Normally, Chrome and Safari simply throw a warning, but still load the content:
```
This content should also be served over HTTPS.
```

But an application built with Nativefier blocks the request:
```
This request has been blocked; the content must be served over HTTPS.
```

I struggle with the same problem and haven't found a solution. Maybe someone else could suggest a solution?

**Comment by jiahaog** [comment] 2016-02-18 17:22
Yup, this is a duplicate of #99

**Closed by jiahaog** 2016-02-18 17:22 UTC
