### ISSUE TITLE
--crash-reporter option crashes packaged app at startup, due to unspecified CompanyName

### ISSUE THREAD

**Issue by zucher** [jiahaog/nativefier#353] opened 2017-04-28 20:39 UTC
### Description
On application startup a popup windows appears with the title "A JavaScript error occurred in the main process" and associated stack trace

### Steps to Reproduce Issue
Start app with crashReporter activated

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.2.0`
- Version of Node.js (run `$ node --version`): `v6.9.1`
- OS: `OSX 10.12.1`
- Architecture `x64`
- Stack trace from the error message (if any)

```
Get the error:
Uncaught Exception:
Error: companyName is a required option to crashReporter.start
    at CrashReporter.start (/Users/vbaillea/git/otlite_desktop/electron/Rainbow-darwin-x64/Rainbow.app/Contents/Resources/electron.asar/common/api/crash-reporter.js:43:13)
    at App.<anonymous> (/Users/vbaillea/git/otlite_desktop/electron/Rainbow-darwin-x64/Rainbow.app/Contents/Resources/app/lib/webpack:/app/src/main.js:67:23)
    at emitOne (events.js:96:13)
    at App.emit (events.js:188:7)
```

**Comment by ronjouch** [comment] 2017-05-01 22:54
Bug reproduced, see https://github.com/jiahaog/nativefier/pull/231 for initial implementation and [electron / crashreport api docs](https://github.com/electron/electron/blob/master/docs/api/crash-reporter.md), which state that companyName is optional, but apparently it's not.

```
~ nativefier --name "nddg" --crash-reporter "http://somecrashreporturl.com" "https://start.duckduckgo.com/" && ./nddg-linux-x64/nddg
Packaging app for platform linux x64 using electron v1.6.6
App built to /home/ronj/nddg-linux-x64
A JavaScript error occurred in the main process
Uncaught Exception:
Error: companyName is a required option to crashReporter.start
    at CrashReporter.start (/home/ronj/nddg-linux-x64/resources/electron.asar/common/api/crash-reporter.js:43:13)
    at App.<anonymous> (/home/ronj/nddg-linux-x64/resources/app/lib/webpack:/app/src/main.js:68:19)
    at emitOne (events.js:96:13)
    at App.emit (events.js:188:7
```

**Comment by dipenpatel235** [comment] 2017-06-15 16:33
hello..
is there any chance to fix fix this bug as urgent. ?
because i am looking for this feature because i want to publish my app.
so i cant ask to user why your app is crash and give log.
so i think if you give some fix pathch version so it is very helpful.

thanks

**Comment by ronjouch** [comment] 2017-07-21 19:56
Should be fixed, thanks @githubbob42.

**Closed by ronjouch** 2017-07-21 19:56 UTC
Labels: bug
