### ISSUE TITLE
Help Problem trying to make it work for Spotify.

### ISSUE THREAD

**Issue by mikhoul** [jiahaog/nativefier#442] opened 2017-09-03 00:30 UTC
I tried to make a portable app for Spotify using:

`nativefier "https://play.spotify.com" `

Everything is fine EXCEPT that I have the message "Playback of protected content is not enabled”" instead of the player 😭 .

**Could somebody showe me how to install the missing plugin**  ❓  

I think it's "Widevine" that is missing but I'm not sure about it, I need help of somebody with better knowledge than me on those topics..

**Regards** :octocat:

**Comment by ronjouch** [comment] 2017-09-03 15:12
Closing as duplicate of #440

**Closed by ronjouch** 2017-09-03 15:12 UTC

**Comment by Mach7Seven** [comment] 2017-12-03 15:28
Has this been fixed? 

I see the code in the main.js file in the source, pulling widevine plugin from Chrome 6103163100

```
const WIDEVINE_PATH = '/Applications/Google Chrome.app/Contents/Versions/61.0.3163.100/Google Chrome Framework.framework/Libraries/WidevineCdm/_platform_specific/mac_x64/widevinecdmadapter.plugin';
const WIDEVINECDM_VERSION = '1.4.8.1008';

```

But it is not working. I manage to find that specific version of Chrome, and put it in /Applications. The widevine plugin inside is 1.4.8.1008 (ref. in the main.js source file)

Not working here. I have Nativefier v. 7.5.4

Has this been implemented?
