### ISSUE TITLE
Confusion in the usage of the '-h' flag

### ISSUE THREAD

**Issue by ojengwa** [jiahaog/nativefier#64] opened 2016-01-23 11:46 UTC
Running any command with the shortcut `-h` results in this error:
```
error: option `-h, --height <value>' argument missing
```

By convention, the shortcut `-h` displays the help message for a particular command option. Also, when you 
```
nativefier [options] --help
```
You get something similar to this:
```
  Options:

    -h, --help                      output usage information
   ...
   -h, --height <value>            set window height, defaults to 800px
```
an obvious duplication.

I would like to propose the shortcut flag `-y` (as in the -y-axis) to represent the height.

Great project.

**Comment by bsonntag** [comment] 2016-01-23 15:24
Duplicate of https://github.com/jiahaog/nativefier/issues/30?

**Closed** 2016-01-24 07:37 UTC
