### ISSUE TITLE
Enhancement enable the user to change the target URL and reload

### ISSUE THREAD

**Issue by GitGeoCoder** [jiahaog/nativefier#451] opened 2017-09-18 16:46 UTC
### Description
In case the default target URL is not valid, I have to manually modify the tragetURL inside the nativefier.json, then restart the APP.  It is inconvenient. Is it possible to add a new menu under the Edit,  like "Edit-Change URL"? 
When clicked,  will pop up a  dialog box with a text box, which allow the user to type in a new URL. Then do a reload. 
 

### Details

- Are you nativefying a *public* website?
No.

- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
Yes.

- Full nativefier command used to build your app: `<command here>`
.\node_modules\.bin\nativefier -n "GXP_Platform_Desktop_Client" localhost  --icon "....\nativefier\app\GXP_Platform_Client32x32.png" --show-menu-bar  -e 1.6.8

- Version of Nativefier (run `nativefier --version`): `v0.0.0`
7.4.1

- Version of node.js (run `node --version`): `v0.0.0`
4.0
- OS: `<OS here>`
WINDOWS10
- Error message / stack trace (if any):
N/A
```
<Error message / Stack trace here>
N/A
```

**Comment by ronjouch** [comment] 2017-09-18 16:57
@GitGeoCoder thanks for the feedback 👍, but an app you can use to navigate by pointing at an URL sounds a lot like a browser to me 🙂. Say you build an app you call "gmail", with an associated url and icon and name, which then the user points at hotmail. Confusion ensues. Or else the "rewriting" should enable the user to change all the metadata in addition to the URL (app name, path, icon), which at this point means the app should basically be able to rebuild itself, which sounds like a big invasive change we don't want.

Nativefier's whole purpose is precisely to package and fixate an app to an URL. Closing as wontfix, but feel free to argue and detail use cases you have in mind.

**Closed by ronjouch** 2017-09-18 16:57 UTC
Labels: feature request, wontfix

**Comment by GitGeoCoder** [comment] 2017-09-18 17:21
@ronjouch 
Here is the use case:
There could be multiple instances of the same server in a private LAN. In case one server instance is not functioning, the user would like to switch to another.  The server instance could be like this \\myComputer. 

I tried to use the context menu. But the menu seems not functioning. Like "Open in new window". Nothing happened. I also tried to add a new menu item by modifying(Adding a new menu item) in the ....\node_modules\nativefier\app\src\components\contextMenu\contextMenu.js
      {
        label: 'Change Target URL',
        click: () => {
          if (targetHref) {
            clipboard.writeText(targetHref);
            return;
          }

          mainWindow.useDefaultWindowBehaviour = true;
          mainWindow.webContents.send('contextMenuClosed');
        },
      },

It didn't show up. Any suggestions and tips are appreciated.

**Comment by GitGeoCoder** [comment] 2017-09-18 19:03
@ronjouch Is is possible Nativefier cached the package  somewhere, my change to the menu wasn't taken when packaging again?

**Comment by ronjouch** [comment] 2017-09-18 19:18
> *Is is possible Nativefier cached the package somewhere, my change to the menu wasn't taken when packaging again?*

@GitGeoCoder nope there's no local state apart from what's in `~/.config/<yourapp>-nativefier-<someid>`, (cookies, cache, window state). You probably omitted to rebuild nativefier itself before re-building your app. See our [developer docs](https://github.com/jiahaog/nativefier/blob/master/docs/development.md)

> *There could be multiple instances of the same server in a private LAN. In case one server instance is not functioning, the user would like to switch to another.*

To me, that's the problem deserving fixing, via your IT (some routing / reverse proxy solution dispatching requests to whatever instance is available). I stand by the feeling that supporting what you're asking for goes against Nativefier core promise. You're asking for genericity to an app whose first "selling point" is simplicity: *"Make any web page a desktop application"*. It's not a generic browser, if you need generic, use a browser 🙂.

**Comment by GitGeoCoder** [comment] 2017-09-18 19:49
@ronjouch I may misunderstood how nativefier works. 
I thought the modified *.js file in the .\node_modules\nativefier\app\src\components will be used and replace the ones in electron automatically without rebuild nativefier.  Why a rebuild is needed? Will try the rebuild next anyway.

**Comment by GitGeoCoder** [comment] 2017-09-18 22:05
@ronjouch I can't get the build going following
https://github.com/jiahaog/nativefier/blob/master/docs/development.md

Error message:
0 info it worked if it ends with ok
1 verbose cli [ 'V:\\TrustedApp\\GXP_Platform\\components\\nodejs\\node.exe',
1 verbose cli   'V:\\TrustedApp\\GXP_Platform\\components\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.14.4
3 info using node@v4.1.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild nativefier@7.4.1
6 info build nativefier@7.4.1
7 verbose unsafe-perm in lifecycle true
8 info nativefier@7.4.1 Failed to exec build script
9 verbose stack Error: nativefier@7.4.1 build: `gulp build`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (V:\TrustedApp\GXP_Platform\components\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (V:\TrustedApp\GXP_Platform\components\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid nativefier@7.4.1
11 verbose cwd C:\TrustedData\git\nativefier
12 error Windows_NT 10.0.10240
13 error argv "V:\\TrustedApp\\GXP_Platform\\components\\nodejs\\node.exe" "V:\\TrustedApp\\GXP_Platform\\components\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
14 error node v4.1.2
15 error npm  v2.14.4
16 error code ELIFECYCLE
17 error nativefier@7.4.1 build: `gulp build`
17 error Exit status 1
18 error Failed at the nativefier@7.4.1 build script 'gulp build'.
18 error This is most likely a problem with the nativefier package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp build
18 error You can get their info via:
18 error     npm owner ls nativefier
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by GitGeoCoder** [comment] 2017-09-19 04:03
@ronjouch I have tried if move the Nativefier directory into the .nodemodules directory of nodejs installation, then no error message when building. Is it required to be in the nodemodules directory?

**Comment by ronjouch** [comment] 2017-09-19 16:00
> *I have tried if move the Nativefier directory into the `node_modules` directory of nodejs installation, then no error message when building.  Is it required to be in the nodemodules directory?*

@GitGeoCoder nope, not sure what's going on with your setup :-/ . I just tested a build on a Windows 10 machine and Node 8.5.0, all smooth.

**Comment by GitGeoCoder** [comment] 2017-09-19 18:13
@ronjouch  
When I run the created APP, I got the following error:
Uncaught Exception:
....\import 'source-map-support/register'
SyntaxError: Unexpected token import 

Any idea?

**Comment by GitGeoCoder** [comment] 2017-09-20 19:43
@ronjouch
In Windows 10, I did a fresh build.
1) Open a CMD window with Admin privilege
2) git clone https://github.com/jiahaog/nativefier.git
3) cd nativefier
4) npm install

npm WARN package.json nativefier@7.4.1 No bin file found at lib/cli.js

error message
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "V:\\TrustedApp\\XXX\\components\\nodejs\\node.exe" "V:\\TrustedApp\\XXX\\components\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! path V:\TrustedApp\GXP_Platform\components\nodejs\node_modules\nativefier\lib\cli.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod


I did not see the nativefier\lib directory in the repo. Where the lib directory come from?

**Comment by ronjouch** [comment] 2017-09-20 20:00
> *Where the `lib` directory come from?*

It is created at CLI build time; https://github.com/jiahaog/nativefier/blob/master/gulp/helpers/src-paths.js#L7

**Comment by GitGeoCoder** [comment] 2017-09-20 20:51
Why "npm install" need it even before the "build" ? 
Or the lib directory is created by npm install?

**Comment by GitGeoCoder** [comment] 2017-09-21 14:22
@ronjouch
Finally, I succeed using Node 8.5.0, same as you do. Node 4.0 and 6.11.3 all failed.
Should the Node version be described in
https://github.com/jiahaog/nativefier/blob/master/docs/development.md

Otherwise, developer will be misleaded by thinking Node >4.0  should work.   Actually, it's not.

**Comment by ronjouch** [comment] 2017-09-21 14:37
> *Otherwise, developer will be misleaded by thinking Node >4.0 should work. Actually, it's not.*

README states we support Node 4.x, and we have continuous integration that tests all builds under 4.x ([example build](https://travis-ci.org/jiahaog/nativefier/builds/265174234)). You must be stumbling on a more specific bug (maybe the Windows + Node 4.x combo? I'll try it). Thanks for the report 👍.

**Comment by GitGeoCoder** [comment] 2017-09-21 14:56
6.11.3 is failing too!

**Comment by ronjouch** [comment] 2017-09-21 17:46
@GitGeoCoder failing build on Windows + Node 6.11.3 reproduced, thanks. It fails on a parsing issue with `mime-db\db.json`, and when [googling at it](https://encrypted.google.com/search?q=module%20parse%20failed%20mime-db%5Cdb.json%20unexpected%20token), it looks like the culprit is `npm`. For me, upgrading npm with `npm install -g --upgrade npm` got me npm 5.4.2, which correctly installed our deps, and `npm run build` was successful. Could you give it a try (please scrap the `node_modules`, `app/node_modules` folders before) and confirm?

@jiahaog looks like old `npm`s suck at handling modules in the dependency tree have the same dependency (just repeating stuff I read in one of the issues found at the aforementioned Google search, I haven't investigated it further). Given the build *does* work even for old npms under Linux, it would suck to force a recent npm, and I like the fact that we only require a **node** version. Any ideas apart from adding a warning to `README.md` and `development.md`?

Tangentially, I love `package-lock.json` for the locking, but I hate it for making pull requests management more painful (inevitable conflicts, have to rework the lock file them before merging). 

- Would we consider going back to non-locked dependencies (but at least with strict direct deps, i.e. `1.2.3` and no `^1.2.3`) ?
- Alternatively, do you have convenience tips to handle `package-lock.json` in projects like ours?
    - If we stick with them, having a `master` push bit would ease up the job for me, as I could "accept" lock-changing PRs by closing them, cloning them locally, adding the `package-lock.json` babysitting commit and merging that.

**Comment by jiahaog** [comment] 2017-10-03 02:23
@ronjouch Yeah, I'm not too certain what the exact problem is requiring us to use a package lock, my guess is one of the upstream dependencies were updated but is not backward compatible 😅 that I've added the package lock to workaround in 33fe71a85557a8be204e7d2b3867793c5719fc77.

> Alternatively, do you have convenience tips to handle package-lock.json in projects like ours?

Hmm, I'm not really keeping up with the current PRs, could you refer me to some of them which have this problem? 

> Would we consider going back to non-locked dependencies (but at least with strict direct deps, i.e. 1.2.3 and no ^1.2.3) ? (Real question, not a suggestion, it's probably a Bad Idea ©)

We could try this solution and see if things still work on an older version of NPM. Definitely do agree with you that requiring a Node version should be sufficient, and forcing a NPM upgrade is not desired

**Comment by GitGeoCoder** [comment] 2017-10-10 17:23
@ronjouch I am trying to add a sub menu in the "Edit" menu to allow my APP user to change the target URL.  What's the minimum steps to do this? I have modified "node_modules\nativefier\app\lib\main.js", but have to regenerate main.js.map.  If you can point me to an existing example, that's great!

**Comment by GitGeoCoder** [comment] 2017-10-10 18:31
@ronjouch I am just back from vacation. Confused a bit. I realized taht I have to rebuild Nativefier in order to add a menu.

**Comment by GitGeoCoder** [comment] 2017-10-19 18:29
@ronjouch  Hi! I finally added the menu->Edit Current URL upon the request of my work.  Thanks a lot for the help.

**Comment by ronjouch** [comment] 2017-10-22 17:48
@GitGeoCoder sure! Awesome you found a solution 👍🙂.

**Comment by TranDinhKhang** [comment] 2018-03-28 09:21
@GitGeoCoder can you share your work, I need a practice for dynamically change targetURL, too. :100:
