### ISSUE TITLE
Support associating app to custom protocol ("deep linking")

### ISSUE THREAD

**Issue by thebold1** [jiahaog/nativefier#574] opened 2018-04-17 13:12 UTC
Hi,

can I integrate deep linking with Nativefier?

There is already a solution for Electron here https://github.com/oikonomopo/electron-deep-linking-mac-win. Where does natively save the main.js and package.json files or does natively generate them each time?

**Comment by bacongravy** [comment] 2018-04-19 18:26
This seems related to #405.  I'm planning on creating a PR to address these two issues.

**Comment by ronjouch** [comment] 2018-04-22 19:59
True, duplicate of #405. Closing that one.

**Closed by ronjouch** 2018-04-22 19:59 UTC
Labels: feature request

**Comment by Kinark** [comment] 2022-03-25 17:12
This is not closed just like the #405 , you guys closed both issues and the bug still goes on.

**Comment by ronjouch** [comment] 2022-03-27 13:49
> This is not closed just like the #405 , you guys closed both issues and the bug still goes on.

See https://github.com/nativefier/nativefier/issues/405#issuecomment-1079935675
