### ISSUE TITLE
Blank window for Nativefied Youtube

### ISSUE THREAD

**Issue by princejosuah** [jiahaog/nativefier#453] opened 2017-09-22 19:14 UTC
### Description

I've nativefied a bunch of sites (Reddit, Inoreader, LinkedIn, Twitter, etc.). All of them went well.
All ? Nope. YouTube still gives me a blank screen on opening.
Does it have any link with #408 i-e related to Google sites ?

### Steps to reproduce issue
`nativefier --name "YouTube" "https://www.youtube.com"`

### Details
- Full nativefier command used to build your app: `nativefier --name "YouTube" "https://www.youtube.com"`
- Version of Nativefier : `v7.4.1`
- Version of node.js : `v8.5.0`
- OS: `macOs 10.12.6`

**Comment by ronjouch** [comment] 2017-09-23 13:46
@princejosuah sadly, can't reproduce the issue here. Can you:

1. Try with a recent Electron, e.g,. `--electron-version 1.8.0`
2. Open the DevTools (Cmd+Shift+I) and paste here any error in the `Console` + any failing `Network` requests?

**Comment by princejosuah** [comment] 2017-09-25 19:58
Thanks for replying. A few internet ups-and-downs later, I've just tried. It doesn't work.
The latest Electron to date is 1.7.8 (1.8.0 threw an error) but still the same behaviour.

The other part seems a bit technical to me. I've opened the dev tools (Cmd + Opt + I finally) but in the browser (Opera 46), right ? There's no such thing in the nativefied app.
I can see twice the same error message : 'Failed to load resource: net::ERR_BLOCKED_BY_CLIENT'.

Hope I haven't put everything upside down 🙄

**Comment by ronjouch** [comment] 2017-09-25 20:09
> *I've opened the dev tools (Cmd + Opt + I finally) but in the browser (Opera 46), right ? There's no such thing in the nativefied app.*

@princejosuah no, I need you to open the DevTools *in the Nativefied app*. Devtools should work here with the same `Command+Option+I`, and should look similar to the ones in Opera. Can you retry?

**Comment by princejosuah** [comment] 2017-09-25 20:33
Oh, sorry. Done now.
No error message in the Console. No message, in fact.
Just `/Users/[MyUsername]/Youtube-darwin-x64/Youtube.app/Contents/Resources/app/lib/static/preload.js:86` followed by `nativefier.json > Object`  And that's all.

**Comment by ronjouch** [comment] 2017-09-25 20:58
@princejosuah any aborted (red) requests in the `Network` tab?

**Comment by princejosuah** [comment] 2017-09-25 21:05
@ronjouch No request in the `Network` tab, totally empty.

**Comment by ronjouch** [comment] 2017-09-25 21:07
> *No request in the Network tab, totally empty.*

@princejosuah hmmm, certainly because you opened the DevTools *after* page finished loading 🙂. With the devtools open, refresh the page with `Cmd`+`R`. Still no requests?

**Comment by princejosuah** [comment] 2017-09-25 21:43
Ok, I've tried to hit `Cmd` + `R` but the result just flashes and doesn't stay on the screen.
So I've done it repetitively enough to read one row in red in a table, as follows
- Column `Name` : `www.youtbe.com`
- Column `Statuts` : `(failed)`
- Column `Type` : `document`
- Column `Initiator` : `Other`
- Column `Size` : `0B`
- Column `Time` : `5ms`.

I don't know if it helps...

PS : Thank you for taking the time to try to solve this.

**Comment by ronjouch** [comment] 2017-10-03 15:43
>Name : www.youtube.com, Status : (failed), Type : document, Initiator : Other, Size : 0B, Time : 5ms.
>
> I don't know if it helps...

@princejosuah it does, and having this first row show `Status: (failed)` and `Size : 0B` is 101% anormal. Can you click that failed line and report/screenshot the full details (headers, response) of the request/response panel that will display on the right?

**Comment by princejosuah** [comment] 2017-10-04 15:13
Hi @ronjouch 

As I've stated, that line doesn't stand still, it appears for a tenth of second when I refresh. Not long enough for a screenshot.

Another (hopefully important) update : this issue occurs **only with Google services**. I've just tried with Keep, Gmail, Search, etc. Same thing as for Youtube.

**Comment by ronjouch** [comment] 2017-10-06 14:19
Closing as I can't reproduce the issue (tried multiple configs and multiple OSes), there isn't much I can do. May be something specific to your machine :-/ . Feel free to chime in with more info.

**Closed by ronjouch** 2017-10-06 14:19 UTC
Labels: cannot reproduce

**Comment by ThatFatPat** [comment] 2019-04-04 17:11
Having the exact same issue with a non-Google website. Please reopen

**Comment by dschotman** [comment] 2020-02-28 11:06
Same here. Trying to access a local installation of GitLab which is http loading over https.
````
Request URL: https://gitlab.local/
Referrer Policy: no-referrer-when-downgrade
Provisional headers are shown
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.121 Safari/537.36
````

It might have something to do with automatically upgrating http to https because the security tab shows:
````
This page is not secure (broken HTTPS).

Certificate - Subject Alternative Name missing
The certificate for this site does not contain a Subject Alternative Name extension containing a domain name or IP address.
View certificate

Certificate - missing
This site is missing a valid, trusted certificate (net::ERR_CERT_AUTHORITY_INVALID).
View certificate
````

**Comment by dschotman** [comment] 2020-02-28 11:22
Never mind. I fixed it using the flags `--insecure --ignore-certificate` when creating the app

**Comment by gaving** [comment] 2020-05-12 08:37
This is a long shot, but does anybody know how to debug a launch that just shows a blank screen with no requests? Seems intermittent and I think something to do with my URL.

And then with CTRL+R everything works as normal...

**Comment by gaving** [comment] 2020-05-12 14:09
So for any other poor sod trying to debug this sort of thing, the below might help.

Open your apps directory `resources/app/lib/main.js` and do the debugging in there.

In particular add a:-

```javascript
electron_1.app.commandLine.appendSwitch('log-net-log', 'error.txt')
```

entry up near the `let mainWindow` statement.

Launch the app, close it.

This led me to getting the following error in a error.txt file:-

```json
{"params":{"error_code":"13 (HTTP_1_1_REQUIRED)","stream_id":3},"phase":0,"source":{"id":14,"type":9},"time":"356354574","type":194},
{"params":{"description":"Closing session because server reset stream with ERR_HTTP_1_1_REQUIRED.","net_error":"ERR_HTTP_1_1_REQUIRED","stream_id":3},"phase":0,"source":{"id":8,"type":1},"time":"356354574","type":222},
{"params":{"description":"HTTP_1_1_REQUIRED for stream.","net_error":-365},"phase":0,"source":{"id":14,"type":9},"time":"356354574","type":208},
{"params":{"description":"Abandoned.","net_error":"ERR_HTTP_1_1_REQUIRED","stream_id":3},"phase":0,"source":{"id":8,"type":1},"time":"356354574","type":222},
```

This lead to me sticking a `did-fail-load` handler down after the

```
mainWindow.loadURL("....")
```

line.

This then gave me a `errorCode`, `errorDescription` and `validatedURL`:-

```javascript
mainWindow.webContents.on('did-fail-load', (e, errorCode, errorDescription, validatedURL) => {
    const devToolsLog = s => {
      if (mainWindow && mainWindow.webContents) {
        mainWindow.webContents.executeJavaScript(`console.log("${s}")`);
      }
    };

    devToolsLog(errorCode);
    devToolsLog(errorDescription);
    devToolsLog(validatedURL);
});
```

Which gave me an errorCode of `-9` and `ERR_UNEXEPECTED` description I could
Google.

In my particular scenario I this lead me to https://gitlab.com/gitlab-org/gitlab/-/issues/32127 and ultimately:- 
https://github.com/electron/electron/issues/14978 which indicated there is a Chrome bug in my environment with NTLM and HTTP2.

Adding the following in to the switches at the top sorted it out.

```javascript
electron_1.app.commandLine.appendSwitch('disable-http2');
```

I intend on opening a MR to add that switch shortly.

![](https://i.giphy.com/media/1BXa2alBjrCXC/giphy.webp)
