### ISSUE TITLE
Notifications on Windows don't use App Name

### ISSUE THREAD

**Issue by skoshy** [jiahaog/nativefier#388] opened 2017-06-18 00:10 UTC
### Description
When making a nativefied app and receiving a notification on Windows, the app name is set to "Electron", not the app's actual name.

This shows up in the notification and the action center.

![image](https://user-images.githubusercontent.com/369825/27257116-ed4692a0-5398-11e7-91b7-e7e92e0252da.png)
![image](https://user-images.githubusercontent.com/369825/27257119-fabd9776-5398-11e7-9a9b-dee4f40491d5.png)

### Steps to Reproduce Issue
Make an app and trigger a notification on Windows.

**Comment by ronjouch** [comment] 2017-06-18 00:51
@skoshy thanks for the feedback! Closing, as duplicate of https://github.com/jiahaog/nativefier/issues/28

**Closed by ronjouch** 2017-06-18 00:51 UTC
