### ISSUE TITLE
Remember credentials for basic HTTP authentication

### ISSUE THREAD

**Issue by yandd** [jiahaog/nativefier#328] opened 2017-03-15 09:55 UTC
### Steps to Reproduce Issue

```
nativefier -e 1.6.6 --name "testauth" "https://www.httpwatch.com/httpgallery/authentication/" && ./testauth-linux-x64/testauth
```

Click "Display image", enter login/password httpwatch/whatever, login.

Expected: a prompt proposes remembering the login/password

Actual: it's impossible to remember basic HTTP auth l/p.

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.1.0`
- Version of Node.js (run `$ node --version`): `v7.8.0`

**Comment by ronjouch** [comment] 2017-04-08 02:07
Duplicate of #275, closing this one.

**Closed by ronjouch** 2017-04-08 02:07 UTC
Labels: feature request
