### ISSUE TITLE
Error: companyName is a required option to crashReporter.start

### ISSUE THREAD

**Issue by dipenpatel235** [jiahaog/nativefier#374] opened 2017-05-24 10:21 UTC
### Description
in linux server i have build application for windows.
i have setup done with electron crash report server

so get below error
Error: companyName is a required option to crashReporter.start

### Steps to Reproduce Issue

i have build app using below command.

nativefier --arch 'ia32' --platform "windows" --name "MyCOmpany" "https://www.hello.com" --crash-reporter "https://dasp-fsqrd-73240.herokuapp.com/"

then downloaded that app in windows 32 bit and start app.

so get below error
Error: companyName is a required option to crashReporter.start

### Specifications
 nativefier --version  7.3.1
node --version  v6.10.2
- OS: `centos 7`
- Architecture `X64`

**Comment by ronjouch** [comment] 2017-05-24 13:02
Hey @dipenpatel235, thanks for the feedback! That's a duplicate of known issue https://github.com/jiahaog/nativefier/issues/353 , closing.

**Closed by ronjouch** 2017-05-24 13:02 UTC

**Comment by dipenpatel235** [comment] 2017-05-24 13:09
Okey..
Thanks and sorry for create duplicate.
So u mean that bug is under development ?

Thanks.
