### ISSUE TITLE
Low resolution icon in Plank launcher

### ISSUE THREAD

**Issue by smensak** [jiahaog/nativefier#345] opened 2017-04-15 20:18 UTC
### Description

Currently using Plank dock on KDE plasma and each app created has really low resolution icon. Same results for default ones and with use of -i or --icon. Plank icon size setting is 44px, screen res. is 1980x1080.

### Steps to Reproduce Issue

Create app, have look at icon in Plank.

### Specifications
- Version of Nativefier v7.1.0
- Version of Node.js v7.7.3
- OS: Arch linux
- Architecture: x64

**Comment by ronjouch** [comment] 2017-04-16 00:24
@smensak thanks for the feedback; I first thought of HiDPI trouble, but given your resolution that's not the case.

* Could you attach a screenshot?
* Is the issue specific to Plank? In other terms, is the icon looking good in the KDE/Plasma switcher?

**Comment by smensak** [comment] 2017-04-20 22:12
Issue is Plank specific as far as I can tell. It seems to have something to do with a way Plank threat apps without .desktop file. So maybe not bug on your side but it's hard to tell for me... 

 To "fix it" one can write .desktop file manually and it seems to work then.

Screenshot (notice the blurry google icon on left)
![screenshot](https://cloud.githubusercontent.com/assets/27579955/25254417/c0a9273a-2625-11e7-9d68-751f6fee844c.png)

**Comment by jiahaog** [comment] 2017-05-04 14:24
@smensak Could you elaborate more about the .desktop file as a workaround?

**Comment by smensak** [comment] 2017-05-04 17:52
@jiahaog 
You simply need to create Your_App_Name.desktop for desired app and specify your desired icon. 

For more info abouth .desktop see [.Desktop entry specification](https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html)
Example, for messenger.com:

FILE NAME: messenger.desktop
LOCATION: usr/share/applications (could be any folder)
FILE CONTENT:

[Desktop Entry]
Name=FB messenger
Comment=Facebook messenger
GenericName=Messenger
Exec=/home/user/nativefier/messenger-linux-x64/messenger (path to app executable)
Terminal=false
Type=Application
Icon=fbmessenger (use absoute path or just icon name, there is some algorithm to locate desired icon)
Categories=Network;Chat;
StartupNotify=true

**Comment by ronjouch** [comment] 2017-10-06 17:50
Closing as duplicate of https://github.com/jiahaog/naivefier/issues/204

**Closed by ronjouch** 2017-10-06 17:50 UTC
Labels: bug, linux

**Comment by djom20** [comment] 2018-09-21 15:40
Please @ronjouch Could you share with us which should be the resolution and size of the icon that we must use?
