### ISSUE TITLE
chrome comand line args

### ISSUE THREAD

**Issue by diegonakamashi** [jiahaog/nativefier#472] opened 2017-10-26 20:12 UTC
Is there a way to pass chrome comand line args like ``` --kiosk-printing``` to the app

Any help is highly appreciated :)

**Comment by ronjouch** [comment] 2017-10-26 20:35
@diegonakamashi not for now, no. Help welcome 🙂. Closing as duplicate of https://github.com/jiahaog/nativefier/issues/131

**Closed by ronjouch** 2017-10-26 20:35 UTC
