### ISSUE TITLE
Unable to play video on Netflix, missing component WidevineCdm

### ISSUE THREAD

**Issue by rjmette** [jiahaog/nativefier#649] opened 2018-07-07 14:14 UTC
### Description

Generated an App for Netflix.  When attempting to play a video this error is displayed.

#### Missing Component
We cannot find all the required components to play Netflix on this device. Please visit chrome://components, locate the WidevineCdm component, and click the "Check for update" button.
For additional assistance resolving this issue, please visit our Help Center. https://help.netflix.com/support/27451

### Steps to reproduce issue

Open Netflix.app, play any video.

### Details

- Are you nativefying a *public* website? YES
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? YES
- Full nativefier command used to build your app: `nativefier --name "Netflix" "https://netflix.com"`
- Version of Nativefier (run `nativefier --version`): `v7.6.4`
- Version of node.js (run `node --version`): `v6.14.2`
- OS: `MacOS 10.13.5`

**Comment by sebastienvercammen** [comment] 2018-07-07 16:58
Some extra info: [Requires Widevine CDM for Electron](https://electronjs.org/docs/tutorial/using-widevine-cdm-plugin). This requires regular Chrome to be installed (to get a legal/licensed copy of the plugin).

**Comment by ronjouch** [comment] 2018-07-10 19:09
Closing as duplicate of #435 and https://github.com/jiahaog/nativefier/pull/440

**Closed by ronjouch** 2018-07-10 19:09 UTC
