### ISSUE TITLE
Hangouts "chat pop out" feature doesn't work

### ISSUE THREAD

**Issue by jmdacruz** [jiahaog/nativefier#489] opened 2017-11-16 20:20 UTC
### Description

Google hangouts (https://hangouts.google.com/) allows you to "pop out" chat windows (i.e., open chats on a separate window). This feature seems to be broken, the current behavior is that a window is opened, but it does not load the content of the chat (it remains blank).

### Steps to reproduce issue

Create an application using:

```shell
nativefier https://hangouts.google.com/
```

Run the application, login with your Google credentials. Open a chat, and try to pop the chat out by pressing on the arrow (as shown below)

![image](https://user-images.githubusercontent.com/1178370/32913791-433197a4-cac8-11e7-8dbc-2e97d8d86b8c.png)

### Details

- Are you nativefying a *public* website? **yes**
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? `yes, but there is nothing obvious`
- Full nativefier command used to build your app: `nativefier https://hangouts.google.com/`
- Version of Nativefier (run `nativefier --version`): `v7.5.1`
- Version of node.js (run `node --version`): `v6.11.1`
- OS: `macos 10.13`

**Comment by ronjouch** [comment] 2017-11-16 20:45
Hi @jmdacruz and thanks for the feedback 👍. This is a known issue, closing as duplicate of #408. Feel free to follow discussion there, and fix attempts welcome. I tried digging the problem a few days ago and haven't got anything yet; the popup original contents (some html embedding a js payload and an iframe) are loaded but for some reason the rest of the load cascade stays interrupted at this point.

**Closed by ronjouch** 2017-11-16 20:45 UTC
