### ISSUE TITLE
[Question] How to inject javascript or css?

### ISSUE THREAD

**Issue by geeeeeeeeek** [jiahaog/nativefier#141] opened 2016-02-19 03:56 UTC
I wonder if there is some way for me to inject javascript or css into the page, rather than simply apply `nativefier xxx`?

For example, my target page is `whatsapp.com`, and I want to inject js in the page.

**Comment by jiahaog** [comment] 2016-02-19 04:33
Hi! This is a duplicate of #135

**Closed by jiahaog** 2016-02-19 04:33 UTC

**Comment by thegrubbsian** [comment] 2016-02-25 05:25
Hi, looks like this issue and #135 are both marked as closed.  I was just wondering if this was a feature that was still on someone's radar.  I'd be happy to attempt to fix it but I will need some guidance as to where to start.  Can someone point me in the right direction for a potential patch?

**Comment by jiahaog** [comment] 2016-02-25 06:40
I'm actually working on it right now!

**Comment by jiahaog** [comment] 2016-02-25 07:13
@thegrubbsian this has been added since 166aa8962e791a2dbf734deaac3fcaecaab6fbf6
