### ISSUE TITLE
Exe data not modified to the name provided

### ISSUE THREAD

**Issue by itziks00** [jiahaog/nativefier#383] opened 2017-06-07 05:45 UTC
### Description

Hi, 

When I build the application for windows (exe), and set the name using --name, the name is updated in the following places (Name is 'Testing')
* Title of the window
* Name of the window on the taskbar.

But the name isn't updated if right clicking on the taskbar, or if opening the exe properties (Shows 'Electron'); see attached pictures.

Is there a way to modified the exe details (File description, Product name etc)?
I'm running the build on Mac but checking it on windows. Tried to build on windows with the same result.

Thanks!

![image](https://user-images.githubusercontent.com/2135116/26863721-04674a9a-4b5d-11e7-8c2c-e93781b1f64d.png)

![image](https://user-images.githubusercontent.com/2135116/26863794-6b98de90-4b5d-11e7-92da-d0bbff73e04e.png)

### Specifications
- Version of Nativefier: `v7.3.1`
- OS: Windows or Mac

**Comment by ronjouch** [comment] 2017-06-07 12:00
Duplicate of https://github.com/jiahaog/nativefier/issues/28 , closing. @itziks00 thanks for the feedback, pls subscribe to the other bug 🙂.

**Closed by ronjouch** 2017-06-07 12:00 UTC
