### ISSUE TITLE
Toggle developer Tools not working

### ISSUE THREAD

**Issue by kiark** [jiahaog/nativefier#1024] opened 2020-08-13 07:23 UTC
Nativefier 9.2.0
node 12.16.1
Win10 version 1909 x64

Step to reproduce issue:

make folder test
nativefier google.com
on ~\test\Google-win32-x64\resources\app\nativefier.json
change "showMenuBar":true

Launch program, crtl+shift+I or with menu nothing happens

**Comment by ronjouch** [comment] 2020-08-18 07:52
Hi @kiark. Closing as couldn't reproduce.

Tsted on both Windows and Linux: after flipping `showMenuBar` to true (by the way, note you don't have to do this manually, you can use nativefier flag `--show-menu-bar`),

1. Menu bar is visible
2. DevTools work, both from Ctrl+Shift+I and menubar.

Please check if something could be wrong on your side, and feel free to come back with more debug info if you're sure the problem lies in Nativefier.

**Closed by ronjouch** 2020-08-18 07:52 UTC
