### ISSUE TITLE
Support for macOS native spell check

### ISSUE THREAD

**Issue by dsemaya** [jiahaog/nativefier#411] opened 2017-07-14 15:22 UTC
### Description
Nativefier should include support for the macOS "Check Spelling While Typing" feature in Edit:Spelling and Grammar.  This feature is in both Safari and Chrome, along with most other Mac apps since it's part of the OS.  

### Steps to Reproduce Issue
Make a Gmail Nativefier app
Compose an email
There are no red lines under misspelled words.  

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.4.0`
- Version of Node.js (run `$ node --version`): `v6.9.1`
- OS: `macOS 10.12.5`
- Architecture `x86`

**Comment by ronjouch** [comment] 2017-07-14 15:34
Duplicate of https://github.com/jiahaog/nativefier/issues/283 , closing.

**Closed by ronjouch** 2017-07-14 15:34 UTC
