### ISSUE TITLE
Electron 3.x.y EoL

### ISSUE THREAD

**Issue by compuguy** [jiahaog/nativefier#825] opened 2019-07-31 18:54 UTC
### Description

As of 7/30/19, Electron 3.x.y is no longer supported (https://electronjs.org/blog/electron-6-0). The default electron build should be bumped up to Electron 4.2.8. This is related to issue #727.

### Steps to reproduce issue

N/A

### Details

- Are you nativefying a *public* website? N/A
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? N/A
- Full nativefier command used to build your app: `<command here>`
- Version of Nativefier (run `nativefier --version`): `v7.6.12`
- Version of node.js (run `node --version`): `v12.7.0`
- OS: `Raspbian 10 Buster`
- Error message / stack trace (if any): N/A

**Comment by axe312ger** [comment] 2019-08-01 08:57
Whatsapp stopped working as well. We need a electron version bump :sweat_smile:

**Comment by compuguy** [comment] 2019-08-01 14:24
@axe312ger Slack has similar issues with the default Electron build. using the `--electron-version `option with `5.0.8 `seems to resolve the issue.

**Comment by axe312ger** [comment] 2019-08-02 12:04
Thanks, helped but still got issues. Moved the answer to #828 to avoid polluting this not really related issue

**Comment by fuzzy76** [comment] 2019-08-07 08:23
At this point, this is probably a duplicate of #727 since that issue is about doing the Electron version bump.

**Comment by fuzzy76** [comment] 2019-08-07 08:30
Can confirm that forcing Electron 5.0.9 fixed https://thelounge.chat, which earlier refused to start (blank window).

**Comment by mxdpeep** [comment] 2019-08-22 10:11
use `--electron-version 6.0.3`

**Comment by ronjouch** [comment] 2019-08-23 03:27
Fixed with Nativefier 7.7.0, which defaults to Electron 5

**Closed by ronjouch** 2019-08-23 03:27 UTC
