### ISSUE TITLE
Can't close app when onbeforeunload is set

### ISSUE THREAD

**Issue by TGotwig** [jiahaog/nativefier#545] opened 2018-02-26 11:56 UTC
### Description

Hey there 🤗
I can't close my compiled regex 101 app.

### Steps to reproduce issue

Run the App,
type something into the field,
click on exit button.

### Details

- Are you nativefying a *public* website? Yes
- Full nativefier command used to build your app: 
nativefier -n "regex101" "https://regex101.com/"
- Version of Nativefier: v7.5.4
- Version of node.js: v9.3.0
- OS: Windows

**Comment by ronjouch** [comment] 2018-02-26 12:51
Hi @TGotwig and thanks for the feedback. Sorry, I can't reproduce the issue. Can you be more precise? Is it the only website that exhibits the problem? Can you try to isolate the problem by comparing to another machine?

**Comment by TGotwig** [comment] 2018-02-26 13:00
In that video you can see the bug:
https://mnithmde-my.sharepoint.com/:v:/g/personal/thomas_gotwig_mni_thm_de/EcpAE3N26GpGrlDW9ynpkDUBaBto72lF1sLtYOdVRrJpxw?e=4D77gm

Yeah I can try it.

**Comment by TGotwig** [comment] 2018-02-26 13:57
I can't run the binary under my Ubuntu 17 VM

Command: `bash regex-101-linux-x64/regex-101` 
Error: `regex-101-linux-x64/regex-101: regex-101-linux-x64/regex-101: cannot execute binary file`

Command: `./regex-101-linux-x64/regex-101` 
Error: `./regex-101-linux-x64/regex-101: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory`

**Comment by ronjouch** [comment] 2018-02-26 14:18
> *"I can't run the binary under my Ubuntu 17.10 VM"*.

@TGotwig nothing wrong with that. Dynamically-linked Linux binaries are not upwards-compatible (and that's why if you distribute them, you usually compile on the oldest CentOS VM that can run your software). Just re-build your app from the VM.

**Comment by TGotwig** [comment] 2018-02-26 17:28
The closing bug also exists in Ubuntu 14.

This sould be the reason for the bug,
appears after you want to close the tab in the browser,
after you typed something in the fields:
<img src="https://user-images.githubusercontent.com/30773779/36685014-5fb1b242-1b22-11e8-85a6-0185d7db4583.png"></img>

**Comment by tsbertalan** [comment] 2018-05-03 17:11
I believe this is also happening to me with Google play music (if I try to close it from a browser tab while music is playing, it gives me a little are-you-sure popup).

**Comment by ronjouch** [comment] 2018-05-17 00:43
Closing as duplicate of https://github.com/jiahaog/nativefier/issues/422

**Closed by ronjouch** 2018-05-17 00:43 UTC
Labels: bug
