### ISSUE TITLE
Support bundling a local folder

### ISSUE THREAD

**Issue by Gitel** [jiahaog/nativefier#262] opened 2016-09-22 15:11 UTC
Hi All,

I have the following directory structure:

```
myapp:
  index.html
  index.js
  index.css
```

All the HTML does is load the JS and CSS.

I'd like to wrap this with Nativifier and run as desktop application (offline).

When I run `nativefier "index.html"` all I get is an empty web page that doesn't load anything (obviously).

How can I do it?

**Comment by ronjouch** [comment] 2017-04-08 03:32
Duplicate of #243 and #296 , closing

**Closed by ronjouch** 2017-04-08 03:32 UTC
Labels: feature request

**Comment by kravenar** [comment] 2019-03-26 19:25
I love this way to close every thread with the "duplicate" thing. But after seeing all the ''duplicates'' what's the magic way to bundle a folder? since every connected thread has been closed without giving proper help.
