### ISSUE TITLE
Netflix WidevineCdm

### ISSUE THREAD

**Issue by LutzPS** [jiahaog/nativefier#225] opened 2016-07-15 07:01 UTC
I can make a package with WidevineCdm?

**Comment by Silent-Hunter** [comment] 2016-07-15 21:25
I too would like to know if Widevine is supported.

**Comment by jiahaog** [comment] 2016-07-18 03:24
This is a duplicate of #113! It's not supported now, but feel free to submit a pull request!

**Closed by jiahaog** 2016-07-18 03:24 UTC

**Comment by quanglam2807** [comment] 2017-01-05 19:33
@LutzPS  @Silent-Hunter  It has been fixed in WebCatalog webcatalog/desktop#4

**Comment by mikhoul** [comment] 2017-09-03 00:52
I'm new with nativefier and I had the same problem with  Spotify, browsing the issue **I think it was fixed** but is have to be approved before going in the main branch: https://github.com/jiahaog/nativefier/pull/440 

Sorry I'm a newbie with github technical terms,

Regards :octocat:
