### ISSUE TITLE
Feature Request: url right click menu

### ISSUE THREAD

**Issue by gesquive** [jiahaog/nativefier#179] opened 2016-04-05 17:44 UTC
In some webapps a "Save link as..." and a "Copy url" option might be needed. Right now, right clicking on   a link brings up a menu with "Open in default browser" and Open in new window".

For example, when there is an attachment in the Outlook Web App it instructs you to right click and save as. An option that is not possible at the moment.

**Comment by jiahaog** [comment] 2016-04-07 12:07
Yeah, some work needs to go into adding more options into the right click menu. I find myself missing some of the basic options that I have with the right click menu from chrome at times

**Comment by sindresorhus** [comment] 2016-07-07 14:50
You might find [electron-context-menu](https://github.com/sindresorhus/electron-context-menu) useful for this. It includes a `Copy Link` item by default.

**Comment by sindresorhus** [comment] 2016-07-07 14:53
This seems like a duplicate of https://github.com/jiahaog/nativefier/issues/95.

**Comment by jiahaog** [comment] 2016-07-18 03:42
Yup! @gesquive please see the duplicate issue!

**Closed by jiahaog** 2016-07-18 03:42 UTC
