### ISSUE TITLE
Icon PNG isn't used in Windows app - Error: rcedit.exe failed with exit code 19

### ISSUE THREAD

**Issue by Fmstrat** [jiahaog/nativefier#487] opened 2017-11-15 16:47 UTC
### Description

Using latest docker image, attempt to use nativefier on Google Voice. App works, but an error is thrown and the icon image is not used.

### Steps to reproduce issue
```
# mkdir compile
# cp icon.png compile
# chmod a+rw compile -R
# cd compile
# docker run -v "${PWD}":/target jiahaog/nativefier --name GoogleVoice -i /target/icon.png -p windows https://voice.google.com /target/
```

### Details

- Are you nativefying a *public* website? Yes? Things work fine, just the icon doesn't.
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? Yes
- Full nativefier command used to build your app: `docker run -v "${PWD}":/target jiahaog/nativefier --name GoogleVoice -i /target/icon.png -p windows https://voice.google.com /target/`
- Version of Nativefier (run `nativefier --version`): `In docker`
- Version of node.js (run `node --version`): `In docker`
- OS: `docker image`
- Error message / stack trace (if any): See below.

This is the entire response:
```
Downloading tmp-1-0-electron-v1.6.6-win32-x64.zip
[============================================>] 100.0% of 52.42 MB (9.53 MB/s)
Packaging app for platform win32 x64 using electron v1.6.6
Error: rcedit.exe failed with exit code 193. wine: created the configuration directory '/home/node/.wine'
wine: configuration in '/home/node/.wine' has been updated.
wine: Bad EXE format for Z:\usr\local\lib\node_modules\nativefier\node_modules\rcedit\bin\rcedit.exe.
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/nativefier/node_modules/rcedit/lib/rcedit.js:68:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)
```

The EXE does work, but there is an error above, and the EXE uses a blue circle for the icon.

**Comment by ronjouch** [comment] 2017-11-15 16:57
@Fmstrat thanks for the feedback. Closing as duplicate of https://github.com/jiahaog/nativefier/issues/375, feel free to look at discussion there.

**Closed by ronjouch** 2017-11-15 16:57 UTC

**Comment by Fmstrat** [comment] 2017-11-15 21:01
@ronjouch Took me a while to figure this out, so perhaps we could add something to the README? Such as:

----
When building Windows EXEs on Linux hosts, icons are not supported due to an issue with rcedit.exe and Wine (see https://github.com/electron/node-rcedit/issues/22). To fix your application icons, after building, alter the EXE's icon by:

1. Grab the latest compiled rcedit.exe from https://github.com/electron/rcedit/releases
2. On a Windows host, run: `rcedit-x64.exe YourExe.exe --set-icon icon.ico`
----

This would be useful since people wouldn't need to fully replicate the environment required to do the full build. They just need to download 1 exe.

**Comment by ronjouch** [comment] 2017-11-16 16:59
@Fmstrat thanks for the followup 🙂. But to be perfectly clear, your claim *"When building Windows EXEs on Linux hosts, icons are not supported"* is incorrect. Here's what I just tested with Nativefier 6fb3b92eb82bec77ff96075b28e5e93987e32b9f, Ubuntu 16.04.3, Wine 2.21:

- `nativefier --arch 'x64' --platform "windows" --name "googwin" "https://www.google.ca/"`  
→ Worked, produced an app that worked under Windows 10 with the inferred Google icon.
- `nativefier --arch 'x64' --platform "windows" --name "googwin" --icon /opt/icon-someicon.png "https://www.google.ca/"`  
→ Worked, produced an app that worked under Windows 10 with my custom icon.

The remaining, reproduced problem is that rcedit indeed fails ***under some Linuxes***, as documented in #375. Until we properly fix the issue, and because people don't read README, the best "documentation" for that would be to catch the `Bad EXE format` exception currently thrown, and cleanly abort with a mention of your workaround. Using your example, it could look like this (proposal after the blank line):

```
Downloading tmp-1-0-electron-v1.6.6-win32-x64.zip
[========================>] 100.0% of 52.42 MB (9.53 MB/s)
Packaging app for platform win32 x64 using electron v1.6.6
wine: configuration in '/home/node/.wine' has been updated.
wine: Bad EXE format

Error: setting Windows icon failed due to format incompatibility between wine and rcedit.
This is a known issue, see https://github.com/jiahaog/nativefier/issues/375
Workaround: grab the latest compiled rcedit from https://github.com/electron/rcedit/releases
and, on a Windows host, run: rcedit-x64.exe YourExe.exe --set-icon icon.ico
Sorry for the inconvenience, help welcome on the known issue :)
```

**Comment by Fmstrat** [comment] 2017-11-16 22:20
Hah, was totally about to fork and do this: https://github.com/jiahaog/nativefier/commit/6e912fe852043dee4151754e5b05be7a1b399b8a

Looks like you have that part covered ;)

**Comment by ronjouch** [comment] 2017-11-16 23:00
@Fmstrat 🙂. Note this just fixes the Docker build, workarounds and better warning/logging about failing on wine64 off-Docker still welcome.
