### ISSUE TITLE
Doesn't work with google account logins on app.asana.com

### ISSUE THREAD

**Issue by theman8631** [jiahaog/nativefier#282] opened 2016-10-28 22:47 UTC
### Description

app.asana.com on "Use google account" loads a blank page that does nothing.  Attempting to load in same window doesn't help.
### Steps to Reproduce Issue

app.asana.com click "Use google account"
### Specifications
- Version of Nativefier: `v7.0.1`
- Version of Node.js: `v6.9.1`
- OS: `Windows 7`

**Comment by mlncn** [comment] 2016-12-14 02:49
Having similar enough issues with Duolingo to report it here.  When able to finally enter username and password in the google login window, the title of the window changed to "Connecting..." and it stayed white and blank for five minutes.  When i tried to reload, Google gave a 405 error and "that's all we know" message.

Getting to the point of making enough progress to even having that error was even weirder:

1. Clicking the "Log in with Google" link opens in my default browser.
2. Right-clicking the "Log in with Google" link and choosing the "Open in new window" option does nothing.
3. Right-clicking another random link on the page and choosing the "Open in new window" option worked.
4. From this new window, clicking on "Log in with Google" opens a new Nativefier window and i was able to enter my Google username and password.

Then the above happened— reloading any of the open Windows did not log me in.  But repeating step four just now to double-check that's what i did caused the apparently successful login to complete, and expanded the new window into a full size Nativefier window with me logged in.

So, uh, it's possible to log in to Duolingo using Google accounts with Nativefier, but much harder than it should be!  Thanks for the work, and hope this bug report / crazy workaround is useful to a developer of Nativefier or other overly-persistent user like myself!

**Comment by shvchk** [comment] 2017-01-23 18:42
@mlncn workaround didn't work for me, but I've found another one — you can set a password for your Asana account even if you login with Google. To do that just use "Forgot your password?" link on login page, enter your Google account email (the one you log in to Asana with), and Asana will send recovery link to this email, click on it and set your password, then use it with your Google account email to log in to Asana with nativefied app.

**Comment by ronjouch** [comment] 2017-04-08 04:37
Duplicate of more general #164, closing this one.

**Closed by ronjouch** 2017-04-08 04:37 UTC

**Comment by tianhuil** [comment] 2019-04-03 22:10
This is a narrow-cast solution which wokred for me and keeps non-google-login links opening externally for **asana**:
```
nativefier --name "Asana" --internal-urls "accounts\.google\.com.*" https://app.asana.com/
```

**Comment by gozzilli** [comment] 2019-10-11 10:37
This used to work up until today but has stopped working for me. Asana redirects to browser for login.
