### ISSUE TITLE
Error: rcedit.exe failed with exit code 193. wine: created the configuration directory

### ISSUE THREAD

**Issue by dipenpatel235** [jiahaog/nativefier#445] opened 2017-09-08 07:22 UTC
### Description

```
[root@itspare ~]#  nativefier --arch 'x64' --platform "windows" --name "Myapp" "https://www.mysite.com" -i ./logo.png --user-agent "webapp_desktop_v1.0.1" --disable-dev-tools --crash-reporter "https://damp-ajdrd-1234.herokuapp.com/"
  packaging [========================================          ] 80%Packaging app for platform win32 x64 using electron v1.6.6
Error: rcedit.exe failed with exit code 193. wine: created the configuration directory '/root/.wine'
Could not load wine-gecko. HTML rendering will be disabled.
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/root/.wine' has been updated.
wine: Bad EXE format for Z:\usr\lib\node_modules\nativefier\node_modules\rcedit\bin\rcedit.exe.
    at ChildProcess.<anonymous> (/usr/lib/node_modules/nativefier/node_modules/rcedit/lib/rcedit.js:68:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
```

### Steps to reproduce issue
install centos 7 64 bit
install nativefire latest version
install wine
fire below command from terminal and replace logo.png image name

nativefier --arch 'x64' --platform "windows" --name "Myapp" "https://www.mysite.com" -i ./logo.png --user-agent "webapp_desktop_v1.0.1" --disable-dev-tools --crash-reporter "https://damp-ajdrd-1234.herokuapp.com/"

### Details

- Are you nativefying a *public* website? -  my own public website
- Full nativefier command used to build your app: `nativefier --arch 'x64' --platform "windows" --name "Myapp" "https://www.mysite.com" -i ./logo.png --user-agent "webapp_desktop_v1.0.1" --disable-dev-tools --crash-reporter "https://damp-ajdrd-1234.herokuapp.com/"`
- Version of Nativefier (run `nativefier --version`): `v7.4.1`
- Version of node.js (run `node --version`): `v6.11.1`
- OS: `centos 7 64 bit`
- Error message / stack trace (if any):

```
  packaging [========================================          ] 80%Packaging app for platform win32 x64 using electron v1.6.6
Error: rcedit.exe failed with exit code 193. wine: created the configuration directory '/root/.wine'
Could not load wine-gecko. HTML rendering will be disabled.
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/root/.wine' has been updated.
wine: Bad EXE format for Z:\usr\lib\node_modules\nativefier\node_modules\rcedit\bin\rcedit.exe.
    at ChildProcess.<anonymous> (/usr/lib/node_modules/nativefier/node_modules/rcedit/lib/rcedit.js:68:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)

```

**Comment by ronjouch** [comment] 2017-09-08 13:35
Closing as duplicate of https://github.com/jiahaog/nativefier/issues/375

**Closed by ronjouch** 2017-09-08 13:35 UTC
