### ISSUE TITLE
[Feature] Output to single EXE + reduce file size

### ISSUE THREAD

**Issue by AlanDu50** [jiahaog/nativefier#437] opened 2017-08-27 11:04 UTC
As a suggestion, when the nativefier produces the 'output', can we have a single executable instead of an executable with many other files? Because this would be easier to distribute.

And also, can we reduce the file size? Maybe by having options to not have certain features on the browser.

Thank you.

**Comment by ronjouch** [comment] 2017-08-27 11:54
@AlanDu50 thanks for the feedback; closing as duplicate of https://github.com/jiahaog/nativefier/issues/342#issuecomment-293705472. Quoting:

> It would be awesome, yeah. But I'll close this for now, it's three levels of needs-upstream-fix away :-/
> 
> * It would be upstream's (electron-packager) job, who closed https://github.com/electron-userland/electron-packager/issues/243 "How can I create self-contained executables in Windows and GNU/Linux?", passing the ball to their upstream electron...
> * ... and electron closed their https://github.com/electron/electron/issues/914 "Atom & App in one executable"...
> * ... with these words about their own upstream (Chromium):
> 
> > *"The structure of Chromium is not designed for putting everything into an executable, and it would take too much effort to do that. So unless that situation in Chromium changed atom-shell won't support this."*
> 
> So, maaaaybe someday, but I wouldn't hold my breath. If you want to go the extra mile, lobbying the Electron/Chromium projects for this feature is probably what would help mosts.

**Closed by ronjouch** 2017-08-27 11:54 UTC
