### ISSUE TITLE
Build fails behind China with ECONNRESET/ETIMEDOUT error

### ISSUE THREAD

**Issue by jingle0927** [jiahaog/nativefier#500] opened 2017-12-01 07:47 UTC
- Full nativefier command used to build your app: `nativefier --name "Wechat" "https://wx.qq.com/"`
- Version of Nativefier (run `nativefier --version`): `v7.5.4`
- Version of node.js (run `node --version`): `v6.3.1-1`
- OS: `deepin`

```
deepin@deepin:~$ nativefier --name "Wechat" "https://wx.qq.com/"
  packaging [==============================                    ] 60%Downloading tmp-111Downloading tmp-11149-0-electron-v1.7.9-linux-x64.zip
[>                                            ] 0.3% of 51.24 MB (412.63 B/s)




Downloading tmp-11149-0-electron-v1.7.9-linux-x64.zip
Error: read ECONNRESET

{ Error: read ECONNRESET
    at exports._errnoException (util.js:1012:11)
Downloading tmp-11149-0-electron-v1.7.9-linux-x64.zip
Error: read ECONNRESET

```

**Comment by ronjouch** [comment] 2017-12-01 09:46
Hi @jingle0927 and thanks for the feedback. Could this be a problem similar to #497 ? Are you behind a proxy/VPN?

**Comment by jingle0927** [comment] 2017-12-04 02:02
@ronjouch   hi   Thanks

 you can see my speed(0.3% of 51.24 MB (412.63 B/s)), so  I'm come from to China

The speed is too slow , So I used the VPN agent

**Comment by jingle0927** [comment] 2017-12-04 02:05
I will try again.

**Comment by jingle0927** [comment] 2017-12-07 06:30
deepin@deepin:~$ nativefier --name "Wechat" "https://wx.qq.com/"
  packaging [==============================                    ] 60%Downloading tmp-274Downloading tmp-2744-0-electron-v1.7.9-linux-x64.zip
Error: connect ETIMEDOUT 52.216.1.248:443

{ Error: connect ETIMEDOUT 52.216.1.248:443
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '52.216.1.248',
  port: 443 }

**Comment by ronjouch** [comment] 2017-12-09 19:51
@jingle0927 looks like a duplicate of #479 to me, please follow discussion there. In the meantime, here's a workaround that could work: download your desired electron version, and place it where our packager will look for it. See https://github.com/jiahaog/nativefier/issues/448

**Closed by ronjouch** 2017-12-09 19:51 UTC

**Comment by jingle0927** [comment] 2017-12-11 05:36
Thanks

**Comment by imydou** [comment] 2020-05-14 03:23
export ELECTRON_GET_USE_PROXY=1 # 值为1或true
export GLOBAL_AGENT_HTTP_PROXY=http://proxy.example.com:1080
export GLOBAL_AGENT_HTTPS_PROXY=https://proxy.example.com:1080
