### ISSUE TITLE
local html file with javascript gives blank screen app

### ISSUE THREAD

**Issue by rohinkumar** [jiahaog/nativefier#343] opened 2017-04-13 15:21 UTC
### Summary Description
Converting newt-web.html and other files downloaded from [stellafane website](http://stellafane.org/tm/newt-web/newt-web.html) gives me blank screen app. 

Tried replacing local path "newt-web.html" to full path like "file:///Users/<username>/path/newt-web.html" throws the following error  

```
/usr/local/lib/node_modules/nativefier/lib/options/normalizeUrl.js:25
        throw 'Your Url: "' + normalized + '" is invalid!';
        ^
```

Directly converting the website link [http://stellafane.org/tm/newt-web/newt-web.html](http://stellafane.org/tm/newt-web/newt-web.html) makes a responsive app through. 

Is there a different method for converting local html files to app?

### Steps to Reproduce Issue

Download all the files given in the link [http://stellafane.org/tm/newt-web/newt-web.html](http://stellafane.org/tm/newt-web/newt-web.html) namely 

newt-web.html
newt-web.css
newt-web.js
newt-save.php
newt-calc.js
newt-file.js
newt-info.js
telescope.ico
newt-specs.js
newt-trace.js
newt-draw.js
newt-help-ap.html
newt-help-scope.html
newt-help-ver.html
newt-help-gpl.html

Put them all in a folder

Move into the folder in a terminal and try

`nativefier newt-web.html`

Also tried 

`nativefier -p osx -a x64 -m -f -n Newt --maximize -i /Users/path-to-icon/icon.icns newt-web.html --ignore-certificate --insecure`

which gave blank screen apps

When tried with various options such as these

`nativefier -p osx -a x64 -m -f -n Newt --maximize -i /Users/path-to-icon/icon.icns /path/newt-web.html --ignore-certificate --insecure`

`nativefier -p osx -a x64 -m -f -n Newt --maximize -i /Users/path-to-icon/icon.icns file:///path/newt-web.html --ignore-certificate --insecure`

and

`nativefier -p osx -a x64 -m -f -n Newt --maximize -i /Users/path-to-icon/icon.icns "file:///path/newt-web.html" --ignore-certificate --insecure`

It throws an error 

`/usr/local/lib/node_modules/nativefier/lib/options/normalizeUrl.js:25
        throw 'Your Url: "' + normalized + '" is invalid!';
        ^`

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.1.0`
- Version of Node.js (run `$ node --version`): `v7.9.0`
- OS: `Mac OS X Sierra 10.12.4`
- Architecture `x64`

**Comment by ronjouch** [comment] 2017-04-13 15:35
Hi @rohinkumar, thanks for the feedback! No, currently there's no way to nativefy local files. Closing this duplicate of https://github.com/jiahaog/nativefier/issues/45, feel free to subscribe to it.

**Closed by ronjouch** 2017-04-13 15:35 UTC
