### ISSUE TITLE
Add a flag for implementing Discord Rich Presence to nativefied apps

### ISSUE THREAD

**Issue by PhantomNimbi** [jiahaog/nativefier#899] opened 2020-02-02 16:29 UTC
### Description

Support Discord Rich Presence [perhaps via a flag such as `--enable-discord-richpresence`] to allow Discord to see what you are watching and or listening to in apps enabled

### Steps to reproduce issue
- Example: 
`nativefier --name "Crunchyroll" "https://crunchyroll.com/" --tray --flash --enable-es3-apis --internal-urls ".*?" --enable-discord-richpresence --inject "custom_css_path_here"`

### Details

- Are you nativefying a *public* website?
yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
yes
- Version of Nativefier (run `nativefier --version`): 
`v7.7.0`
- Version of node.js (run `node --version`): 
`v13.5.0`
- OS: 
`Windows 10 Pro 1909`

**Comment by ronjouch** [comment] 2020-02-03 15:43
Why would you want that?

**Comment by PhantomNimbi** [comment] 2020-02-04 04:41
Because PreMiD [which does it for browsers] doesn't work with nativefied apps.

**Comment by ronjouch** [comment] 2020-02-08 12:21
Closing as duplicate of https://github.com/jiahaog/nativefier/issues/207 .

**Closed by ronjouch** 2020-02-08 12:21 UTC
