### ISSUE TITLE
Blank White Page Appears when internet is not connected

### ISSUE THREAD

**Issue by shagulhameed** [jiahaog/nativefier#519] opened 2018-01-06 11:55 UTC
Description

Blank White Page Appears when internet is not connected .. tell me how can i implement alert message to notify users, when internet is not connected..

--> when users opens the application and if internet is not connected , they could receive the alert message that internet is not connected with exit button

Steps to reproduce issue

1. clear cache memory and close the application
2. disconnect your internet connection
3. open the application

you will see a blank white page appearing !!!

**Comment by ronjouch** [comment] 2018-01-06 16:01
@shagulhameed thanks for the feedback 🙂. Closing as duplicate of #252, feel free to follow the discussion there.

**Closed by ronjouch** 2018-01-06 16:01 UTC

**Comment by shagulhameed** [comment] 2018-01-06 16:29
in #252 , there is no proper solution, please give me an proper solution to this issue
