### ISSUE TITLE
Slimmer applications by sharing framework library

### ISSUE THREAD

**Issue by voltechs** [jiahaog/nativefier#792] opened 2019-04-16 20:09 UTC
### Description
Place `Electron Framework.framework` in `/Library/Frameworks` for smaller app sizes.

### Steps to reproduce issue
N/A

### Details
Once you start creating more than a couple nativefied apps, it gets a bit heavy, duplicating a 120MB framework multiple times

I tried moving the framework myself and symlinking to it, but that doesn't work.

IIRC from my library linking days, the application needs to know to look for the framework in such a path.

**Comment by ronjouch** [comment] 2019-04-19 17:29
Closing as duplicate of https://github.com/jiahaog/nativefier/issues/348

**Closed by ronjouch** 2019-04-19 17:29 UTC
