### ISSUE TITLE
Can't Login With Google Apps

### ISSUE THREAD

**Issue by nlevin** [jiahaog/nativefier#471] opened 2017-10-25 20:56 UTC
### Description

When I try to log in to Asana via Nativefier, it opens up the OAuth dialog in a new window in Chrome, then when I try to log in, it just stalls. I'm assuming the dialog must be loaded inside of the app itself, but I can't figure out a way to do that.

### Steps to reproduce issue

1. nativefier --name Asana asana.com
2. Open Asana
3. Try to login with google

### Details

- Are you nativefying a *public* website? Yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? Yes
- Version of Nativefier (run `nativefier --version`): `v7.4.1`
- Version of node.js (run `node --version`): `v8.8.0`
- OS: `Mac 10.12.6`

**Comment by ronjouch** [comment] 2017-10-25 21:07
@nlevin yeah we have trouble with OAuth logins, sorry about that :-/ . Closing as duplicate of https://github.com/jiahaog/nativefier/issues/164 , feel free to follow-up there, the problem seems to be understood but someone has to put the work.

**Closed by ronjouch** 2017-10-25 21:07 UTC
