### ISSUE TITLE
How to integrate extenstions to nativefiers app?

### ISSUE THREAD

**Issue by luman75** [jiahaog/nativefier#961] opened 2020-04-27 11:10 UTC
**Problem statement**
I need to include into the standalone app chrome extension to be exact grammarly. 
I would be great to make that easily possible with clear process we can reuse for the other extensions. 
Not sure if there is any workaround of that problem now?

**Comment by ronjouch** [comment] 2020-04-27 13:19
Closing as duplicate of https://github.com/jiahaog/nativefier/issues/207

**Closed by ronjouch** 2020-04-27 13:19 UTC

**Comment by exander77** [comment] 2020-04-30 10:23
@luman75 No way to easily do it. Support for an extension from Electron is basically non-existent. The only way how to do it extracts the logic from the extension and make it into the injected script.

I did this for myself in case of KeepassXC. But it is stripped down version.

**Comment by Rimseg** [comment] 2020-10-29 12:17
It's possible and it doesn't take much time see here:
https://github.com/jiahaog/nativefier/issues/246#issuecomment-718708717
