### ISSUE TITLE
Can you please add autofill support

### ISSUE THREAD

**Issue by aashutoshrathi** [jiahaog/nativefier#619] opened 2018-05-25 05:00 UTC
### Description

If we fill the same form multiple time, it should give some suggestion as autofill in chrome 

### Steps to reproduce issue

Login few times to some site and see you get no suggestion for a form like in incognito.

### Details

- Are you nativefying a *public* website? Yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- Full nativefier command used to build your app: `nativefier "github.com"`
- Version of Nativefier (run `nativefier --version`): `v7.6.3`
- Version of node.js (run `node --version`): `v8.11.1`
- OS: `Windows 10`
- Error message / stack trace (if any):

```
<Error message / Stack trace here>
```

**Comment by ronjouch** [comment] 2018-05-25 12:10
Hi @aashutoshrathi and thanks for the feedback. That's a known feature request; closing as duplicate of https://github.com/jiahaog/nativefier/issues/310

**Closed by ronjouch** 2018-05-25 12:10 UTC
