### ISSUE TITLE
Using nativefier under Linux mint to build an exe(win32) is done successfully. But the generated exe can't run. 

### ISSUE THREAD

**Issue by fintechee** [jiahaog/nativefier#1039] opened 2020-09-01 03:45 UTC
**Homework**

- [ ] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [ ] I searched existing issues, open & closed. Yes, my question is new.
- [ ] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Your question**

Using nativefier under Linux mint to build an exe(win32) is done successfully. But it can't run. 
Wine was installed and PATH was configured as well.

**Steps to reproduce**

Build command:
nativefier -n "test1" -p "win32"  "https://www.google.com"

But when I run the generated exe, it's done with errors:

002b:fixme:winsock:WS_EnterSingleProtocolW unknown Protocol <0x00000000>
002b:fixme:winsock:WS_EnterSingleProtocolW unknown Protocol <0x00000000>
002c:fixme:process:NtQueryInformationProcess (0xffffffffffffffff,info_class=49,0xdafb08,0x00000008,(nil)) Unknown information class
002b:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub

002b:fixme:ntdll:EtwEventRegister ({d2d578d9-2936-45b6-a09f-30e32715f42d}, 0x142e745c0, 0xb5e120, 0xb5e138) stub.
002b:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0xb5e150, 16) stub
002b:fixme:nls:GetThreadPreferredUILanguages 00000038, 0x22f334, (nil) 0x22f330
002b:fixme:nls:get_dummy_preferred_ui_language (0x38 0x22f334 (nil) 0x22f330) returning a dummy value (current locale)
002b:fixme:nls:GetThreadPreferredUILanguages 00000038, 0x22f334, 0x22f310 0x22f330
002b:fixme:nls:get_dummy_preferred_ui_language (0x38 0x22f334 0x22f310 0x22f330) returning a dummy value (current locale)
002b:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0034:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 000000000275FDA0
002b:fixme:ntdll:NtQueryVolumeInformationFile 0x200: volume info not supported
002b:fixme:winsock:WSALookupServiceBeginW (0x22ef70 0x00000ff0 0x22efe8) Stub!
002b:fixme:iphlpapi:NotifyAddrChange (Handle 0x22f128, overlapped 0x10251a0): stub
002b:fixme:win:GetPointerDevices (0x22eab4 (nil)): partial stub
002b:fixme:win:GetDisplayConfigBufferSizes (0x2 0x22eab4 0x22eab0): stub
0038:fixme:wtsapi:WTSRegisterSessionNotification Stub 0000000000010056 0x00000001
003e:fixme:security:CreateRestrictedToken (00000000000002BC, 0x0, 4, 0000000002B3E080, 19, 0000000002B3EC30, 5, 0000000002B43370, 000000000BA1EC20): stub
003e:fixme:advapi:SetEntriesInAclW unhandled access mode 4
003e:fixme:ntdll:NtSetInformationToken TokenIntegrityLevel stub!
003e:fixme:security:CreateRestrictedToken (00000000000002BC, 0x0, 0, 0000000000000000, 0, 0000000000000000, 9, 0000000002B3ECD0, 000000000BA1EB90): stub
003e:fixme:advapi:SetEntriesInAclW unhandled access mode 4
003e:fixme:ntdll:NtSetInformationToken TokenIntegrityLevel stub!
003e:fixme:sync:NtSetInformationJobObject stub: 0x2bc 4 0xba1eec8 4
003e:fixme:process:CreateProcessInternalW Creating a process with a token is not yet implemented
003e:fixme:process:CreateProcessInternalW Unsupported attribute 0x20002.
002b:fixme:win:RegisterDeviceNotificationW (hwnd=0x1005e, filter=0x22ee48,flags=0x00000000) returns a fake device notification handle!
002b:fixme:dwmapi:DwmIsCompositionEnabled 000000000022D04C
002b:fixme:win:RegisterTouchWindow (0x10064 00000002): stub
0038:fixme:wtsapi:WTSRegisterSessionNotification Stub 0000000000010058 0x00000000
002b:fixme:dwmapi:DwmSetWindowAttribute (0000000000010064, 2, 000000000022D4F4, 4) stub
003c:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
003c:fixme:file:ReplaceFileW Ignoring flags 2
002b:fixme:time:QueryThreadCycleTime (0xfffffffffffffffe,0x22c700): stub!
002b:fixme:nls:GetThreadPreferredUILanguages 00000038, 0x22cab4, (nil) 0x22cab0
002b:fixme:nls:get_dummy_preferred_ui_language (0x38 0x22cab4 (nil) 0x22cab0) returning a dummy value (current locale)
002b:fixme:nls:GetThreadPreferredUILanguages 00000038, 0x22cab4, 0x22ca90 0x22cab0
002b:fixme:nls:get_dummy_preferred_ui_language (0x38 0x22cab4 0x22ca90 0x22cab0) returning a dummy value (current locale)

**Context**

 - Nativefier: 10.1.0
 - Node.js: 12.9.1
 - Npm:6.10.2
 - OS: Linux mint 19

**Comment by ronjouch** [comment] 2020-09-03 02:38
@fintechee I cannot reproduce the issue, here I was able to successfully build your Google app from Arch and run under Windows 10. With that, closing, feel free to come back with additional info or someone confirming the bug, and I'll re-open.

**Closed by ronjouch** 2020-09-03 02:38 UTC
Labels: question

**Comment by fintechee** [comment] 2020-09-03 05:34
Thank you for your reply.
If you want to reproduce it, please build a windows exe under linux(my dev is linux mint OS).
The build is done successfully, but it can't be run.
If you build linux executable under linux OS, it can be done successfully(both build and run)
