### ISSUE TITLE
Unable to Quit app

### ISSUE THREAD

**Issue by daarmstrong** [jiahaog/nativefier#614] opened 2018-05-22 02:10 UTC
### Description

Unable to quit application as the web-site has a pop-up asking if sure to close (screenshot attached)

### Details

- Are you nativefying a *public* website? No
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? Yes
- Full nativefier command used to build your app: `<command here>`
 nativefier https://dashboard.zopim.com/#home --disable-context-menu
- Version of Nativefier (run `nativefier --version`): `v7.6.1` 
- Version of node.js (run `node --version`): `v8.9.4
![capture](https://user-images.githubusercontent.com/37885928/40338559-5f0542dc-5da8-11e8-8ca1-0464df7e444b.PNG)
`
- OS: `<OS here>`
- Error message / stack trace (if any):

```
<Error message / Stack trace here>
```

**Comment by ronjouch** [comment] 2018-05-22 02:26
Yup, known issue. Closing as duplicate of https://github.com/jiahaog/nativefier/issues/422 / #545

**Closed by ronjouch** 2018-05-22 02:26 UTC
