### ISSUE TITLE
Bug: Unable to Share Screen Discord

### ISSUE THREAD

**Issue by Eisa01** [jiahaog/nativefier#1077] opened 2020-11-29 17:17 UTC
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [x] I searched existing issues, open & closed. Yes, my bug is new.
- [x] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Bug description**

Building a Discord with nativefier breaks the Share Screen functionality.
After clicking on Screen Share during a call, a pop-up with screen share options fails to appear.
Instead, clicking Screen Share displays an error message in Developer tools

**Steps to reproduce**

Give your ***full*** nativefier command and its logs, with the ***`--verbose` flag***, on a ***public*** site:
`nativefier https://discord.com/login --verbose --tray --single-instance`
```
nativefier https://discord.com/login --verbose --tray --single-instance --internal-urls .*
Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.

Performing async options post-processing.
Inferring user agent for electron 10.1.0 / win32
Grabbing electron<->chrome versions file from https://atom.io/download/atom-shell/index.json
Inferring icon for https://discord.com/login on win32
Inferring icon from store for https://discord.com/login on win32
Allowed icon formats when building for win32 (limited on Windows): [ '.ico' ]
Inferring name for https://discord.com/login
Got 249 icons from gitcloud
Max icon match score: 0
No relevant icon in store.
Trying to extract a .ico icon from the page.
Fetched 4.3 kb page at https://discord.com/login
Inferred title: Discord
Sanitized filename for Discord : Discord
Got an icon from the page.
Writing 60.6 kb icon to C:\Users\Eisa\AppData\Local\Temp\nativefier-20-51-45-iconinfer--12420-Wm3IOvlv93L2\icon.png
Associated electron v10.1.0 to chrome v85.0.4183.87
Given chrome 85.0.4183.87 on win32, using user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.87 Safari/537.36

Preparing Electron app...
Copying electron app from C:\Users\Eisa\AppData\Roaming\npm\node_modules\nativefier\app to C:\Users\Eisa\AppData\Local\Temp\nativefier-20-51-45-app--12420-fuf7DNe6PEu5
Writing app config to C:\Users\Eisa\AppData\Local\Temp\nativefier-20-51-45-app--12420-fuf7DNe6PEu5\nativefier.json
No files to inject, skipping copy.
Updating C:\Users\Eisa\AppData\Local\Temp\nativefier-20-51-45-app--12420-fuf7DNe6PEu5\package.json 'name' field to discord-nativefier-888d53

Converting icons...
Failed to convert icon to .ico, skipping. Error: Icon conversion only supported on macOS or Linux. If building for Windows, download/create a .ico and pass it with --icon favicon.ico . If building for macOS/Linux, do it from macOS/Linux
    at C:\Users\Eisa\AppData\Roaming\npm\node_modules\nativefier\src\helpers\iconShellHelpers.ts:26:9
    at new Promise (<anonymous>)
    at iconShellHelper (C:\Users\Eisa\AppData\Roaming\npm\node_modules\nativefier\src\helpers\iconShellHelpers.ts:23:10)
    at Object.convertToIco (C:\Users\Eisa\AppData\Roaming\npm\node_modules\nativefier\src\helpers\iconShellHelpers.ts:72:10)
    at Object.convertIconIfNecessary (C:\Users\Eisa\AppData\Roaming\npm\node_modules\nativefier\src\build\buildIcon.ts:46:30)
    at Object.buildNativefierApp (C:\Users\Eisa\AppData\Roaming\npm\node_modules\nativefier\src\build\buildNativefierApp.ts:116:9)

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
  electron-packager Electron Packager 15.1.0
  electron-packager Node v12.18.4
  electron-packager Host Operating system: win32 10.0.19042 (x64) +0ms
  electron-packager Packager Options: {"arch":"x64","asar":false,"darwinDarkModeSupport":false,"dir":"C:\\Users\\Eisa\\AppData\\Local\\Temp\\nativefier-20-51-45-app--12420-fuf7DNe6PEu5","electronVersion":"10.1.0","icon":"C:\\Users\\Eisa\\AppData\\Local\\Temp\\nativefier-20-51-45-iconinfer--12420-Wm3IOvlv93L2\\icon.png","name":"Discord","out":"C:\\Users\\Eisa\\Desktop","overwrite":true,"platform":"win32","targetUrl":"https://discord.com/login","tmpdir":false,"win32metadata":{}} +1ms
  electron-packager Target Platforms: win32 +4ms
  electron-packager Target Architectures: x64 +1ms
  electron-packager Requiring author in package.json, as CompanyName was not specified for win32metadata +0ms
  electron-packager Inferring appVersion from version in C:\Users\Eisa\AppData\Local\Temp\nativefier-20-51-45-app--12420-fuf7DNe6PEu5\package.json +6ms
  electron-packager Inferring win32metadata.CompanyName from author in C:\Users\Eisa\AppData\Local\Temp\nativefier-20-51-45-app--12420-fuf7DNe6PEu5\package.json +0ms
  electron-packager Application name: Discord +7ms
  electron-packager Target Electron version: 10.1.0 +1ms
  electron-packager Ignored path regular expressions: [ '/\\.git($|/)', '/node_modules/\\.bin($|/)', '\\.o(bj)?$' ] +0ms
  electron-packager Downloading Electron with options {"platform":"win32","arch":"x64","version":"10.1.0","artifactName":"electron"} +0ms
Packaging app for platform win32 x64 using electron v10.1.0
  electron-packager Creating C:\Users\Eisa\Desktop\win32-x64-template +3ms
  electron-packager Extracting C:\Users\Eisa\AppData\Local\electron\Cache\httpsgithub.comelectronelectronreleasesdownloadv10.1.0electron-v10.1.0-win32-x64.zip\electron-v10.1.0-win32-x64.zip to C:\Users\Eisa\Desktop\win32-x64-template +2ms
  electron-packager Initializing app in C:\Users\Eisa\Desktop\Discord-win32-x64 from C:\Users\Eisa\Desktop\win32-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [
  'C:\\Users\\Eisa\\Desktop\\Discord-darwin-x64',
  'C:\\Users\\Eisa\\Desktop\\Discord-darwin-arm64',
  'C:\\Users\\Eisa\\Desktop\\Discord-linux-ia32',
  'C:\\Users\\Eisa\\Desktop\\Discord-linux-x64',
  'C:\\Users\\Eisa\\Desktop\\Discord-linux-armv7l',
  'C:\\Users\\Eisa\\Desktop\\Discord-linux-arm64',
  'C:\\Users\\Eisa\\Desktop\\Discord-linux-mips64el',
  'C:\\Users\\Eisa\\Desktop\\Discord-mas-x64',
  'C:\\Users\\Eisa\\Desktop\\Discord-mas-arm64',
  'C:\\Users\\Eisa\\Desktop\\Discord-win32-ia32',
  'C:\\Users\\Eisa\\Desktop\\Discord-win32-x64',
  'C:\\Users\\Eisa\\Desktop\\Discord-win32-arm64'
] +3s
  electron-packager Renaming electron.exe to Discord.exe in C:\Users\Eisa\Desktop\Discord-win32-x64 +27ms
WARNING: Could not find icon "C:\Users\Eisa\AppData\Local\Temp\nativefier-20-51-45-iconinfer--12420-Wm3IOvlv93L2\icon.ico", not updating app icon
  electron-packager Running rcedit with the options {"version-string":{"OriginalFilename":"Discord.exe","CompanyName":"Jia Hao"},"file-version":"1.0.0","product-version":"1.0.0"} +0ms

Finalizing build...
Copying icons if necessary
Copying icon C:\Users\Eisa\AppData\Local\Temp\nativefier-20-51-45-iconinfer--12420-Wm3IOvlv93L2\icon.png to C:\Users\Eisa\Desktop\Discord-win32-x64\resources\app\icon.png
App built to C:\Users\Eisa\Desktop\Discord-win32-x64 , move it wherever it makes sense for you and run the contained .exe file.
```

**Expected behavior**
The pop-up that should appear when clicking on share screen can be found below:
[https://i.imgur.com/AQeGA1H.png](url)
**Actual behavior**
Please find the error message that is displayed on DevTools when attempting to Screen Share via Nativefier build instead of website.
[https://i.imgur.com/WKnGNuU.png](url)
```
Uncaught (in promise) DOMException: Permission denied @ 779456318913511435:1 
Promise.then (async)
t.default @ a7dcb55c32683bd09ff7.js:8
(anonymous) @ a7dcb55c32683bd09ff7.js:15
onClick @ a7dcb55c32683bd09ff7.js:15
E @ f56d168fce6c3259fa05.js:78
T @ f56d168fce6c3259fa05.js:78
(anonymous) @ f56d168fce6c3259fa05.js:78
O @ f56d168fce6c3259fa05.js:78
L @ f56d168fce6c3259fa05.js:78
N @ f56d168fce6c3259fa05.js:78
C @ f56d168fce6c3259fa05.js:78
On @ f56d168fce6c3259fa05.js:78
ce @ f56d168fce6c3259fa05.js:78
Dn @ f56d168fce6c3259fa05.js:78
Mn @ f56d168fce6c3259fa05.js:78
Pn @ f56d168fce6c3259fa05.js:78
t.unstable_runWithPriority @ f56d168fce6c3259fa05.js:86
zi @ f56d168fce6c3259fa05.js:78
fu @ f56d168fce6c3259fa05.js:78
Ln @ f56d168fce6c3259fa05.js:78
r @ 265525c7fec34cdee9ad.js:16
```

**Context**

 - Nativefier: 10.1.0
 - Node.js: v12.18.4.
 - Npm: 6.14.6
 - OS: Windows 10 Pro, Version 20H2, OS Build 19042.630
 - Is it a regression? If yes, what's the last working / first broken version? N/A
 - Additional context: (for example: "I'm behind a proxy, with configuration X and protocol Y") N/A

**Comment by ronjouch** [comment] 2020-11-29 17:39
Thanks. Closing as duplicate of other screenshare issues https://github.com/jiahaog/nativefier/issues/927 https://github.com/jiahaog/nativefier/issues/971 . Use the official Discord app, it's strictly better as already a well-packaged app.

**Closed by ronjouch** 2020-11-29 17:39 UTC
Labels: bug
