### ISSUE TITLE
wine: can't find rcedit.exe

### ISSUE THREAD

**Issue by BardiaKh** [jiahaog/nativefier#260] opened 2016-09-18 14:20 UTC
### Description

Hello,
I have installed the latest version of wine(v1.9.18) and added it to PATH. But wen I execute the command bellow, the error comes out that wine can't find rcedit.exe but when I use `ls` I can see it in the corresponding directory.

The command:

```bash
nativefier --name "Simorgh" --platform windows --arch x64 --ignore-certificate --maximize --disable-context-menu --conceal --icon ./icon.png  https://simorgh.cloud --inject ./inject.js
```
### Specifications
- Version of Nativefier: `v7.0.1`
- Version of Node.js :`v6.6.0`
- OS: `macOS Sierra`
- Architecture `x64`
- Stack trace from the error message:

```
wine: cannot find '/usr/local/lib/node_modules/nativefier/node_modules/rcedit/bin/rcedit.exe'
```

**Comment by ronjouch** [comment] 2017-04-21 01:39
@BardiaKh we just released Nativefier 7.2.0, which upgrades all our dependencies, and I think I saw a commit mentioning `electron-packager` does a better job at this wine/rcedit thing. Could you please try this new version and report back if the problem persists or is solved? Thanks!

**Comment by ronjouch** [comment] 2017-04-28 23:20
Can't reproduce the issue on 7.2.0, but @BardiaKh note this case triggers bug #233 "Nativefier fails when using options --conceal plus --icon". @BardiaKh closing as the wind issue is no longer reproducible, please try on your side (taking into account #233) and feel free to chime in if 7.2.0 is still KO for you. Thanks for the feedback!

```bash
# Failure: --conceal and --icon
 /opt/n nativefier --name "Simorgh" --platform windows --arch x64 --ignore-certificate --maximize --disable-context-menu --conceal --icon ./icon.png  https://simorgh.cloud --inject ./inject.js
Packaging app for platform win32 x64 using electron v1.6.6
[ { Error: ENOENT: no such file or directory, open '/opt/n/Simorgh-win32-x64/resources/app/icon.ico'
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: '/opt/n/Simorgh-win32-x64/resources/app/icon.ico' } ]

# Success: --conceal without --icon
 /opt/n nativefier --name "Simorgh" --platform windows --arch x64 --ignore-certificate --maximize --disable-context-menu --conceal --inject ./inject.js https://simorgh.cloud
Packaging app for platform win32 x64 using electron v1.6.6
App built to /opt/n/Simorgh-win32-x64

# Success: --icon without --conceal
 /opt/n nativefier --name "Simorgh" --platform windows --arch x64 --ignore-certificate --maximize --disable-context-menu --icon ./icon.png  https://simorgh.cloud --inject ./inject.js
Packaging app for platform win32 x64 using electron v1.6.6
App built to /opt/n/Simorgh-win32-x64
```

**Closed by ronjouch** 2017-04-28 23:20 UTC
Labels: bug, macOS, need info

**Comment by BardiaKh** [comment] 2017-07-21 05:52
Hi
Sorry for the delayed response. I tried to reproduce the issue but I couldn't. 
Think its all crushed!

Thanks...
