### ISSUE TITLE
Allow flags for context menu to be set or change defaults?

### ISSUE THREAD

**Issue by fuzzy76** [jiahaog/nativefier#914] opened 2020-02-27 10:47 UTC
Nativefier uses https://github.com/sindresorhus/electron-context-menu and I'd really like to enable the OS X services meny for my apps. It has alot of OS integrations like adding links directly to my "read later" list, add selection as a reminder, send text to other applications, etc.

This could either be done by setting showServices to true by default, or adding config flags for toggling this.

**Comment by ronjouch** [comment] 2020-02-27 13:31
Closing as duplicate of https://github.com/jiahaog/nativefier/issues/913

**Closed by ronjouch** 2020-02-27 13:31 UTC

**Comment by fuzzy76** [comment] 2020-02-27 13:58
Isn't that issue about adding custom elements? I want the native macOS elements, which can't be implemented in javascript.

**Comment by ronjouch** [comment] 2020-02-27 14:47
Not my understanding, from what I understand you're both asking the same thing.
