### ISSUE TITLE
[question] blank square on load ?

### ISSUE THREAD

**Issue by frlinw** [jiahaog/nativefier#449] opened 2017-09-16 02:24 UTC
### Description

When I open an app, there is a blank square during few ms. Is it possible to avoid it ?

![nativefier-load](https://user-images.githubusercontent.com/11896237/30508409-e01fe186-9a96-11e7-9bcc-92e84a3e1b94.jpg)

**Comment by ronjouch** [comment] 2017-09-18 00:14
@frlinw thanks for the feedback. Looking at your partial screenshot, it looks like the *website* you're nativefying does this. Nativefier has no control over what websites do (or maybe look at `--inject`, you might be able to manually hide this square for your website). If I'm wrong and this behavior exists on all your nativefied apps, then please come back with the minimum details requested by [the issue template](https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE.md).

With that, closing, but will re-open if you find the time to bring details. Cheers!

**Closed by ronjouch** 2017-09-18 00:14 UTC

**Comment by frlinw** [comment] 2017-09-18 00:39
I had some details !
It's a Vue app, the square appear at the very beginning, when the app is not loaded. 
If it's related to my app, I should see the square in my browser too, no ?

**Comment by ronjouch** [comment] 2017-09-18 00:57
@frlinw can't reproduce here:

![factory-noblacksquare](https://user-images.githubusercontent.com/522085/30526555-3aeea31e-9bea-11e7-9a07-7604ef6660ec.gif)

→ I need your help to isolate the problem:

1. Can you try on another machine?
2. On another OS?
3. On another Electron version (e.g. try `--electron-version 1.8.0`)
4. *"If it's related to my app, I should see the square in my browser too, no ?"* → Yup. But does it happen if you nativefy other websites (e.g. try nativefying google.com, same?)

**Comment by frlinw** [comment] 2017-09-18 01:19
Thanks for your help

1. Can't test on other machine
2. tried on ubuntu (virtual machine), it's ok, no square
3. same issue with --electron-version 1.8.0
4. same issue with google.com & facebook.com & the rest of the web

**Comment by ronjouch** [comment] 2017-09-18 01:34
@frlinw hm, thanks for the prompt feedback. That leaves us with a machine/configuration or OS-specific bug. Leaving this closed as it's tough to dig much deeper, but feel free to add anything you think worth mentioning. ¯\\_(ツ)_/¯

Other suggestions: got up-to-date drivers? Could anything (malware / anti-malware) be injecting stuff?
