### ISSUE TITLE
Apple Music: Can't log in

### ISSUE THREAD

**Issue by dsemaya** [jiahaog/nativefier#849] opened 2019-09-06 21:51 UTC
### Description

I can't complete the login process using the new Apple Music Beta site in Nativefier.  Does anyone know if there's a way to make this work?  Maybe some flags that I'm not aware of?

### Steps to reproduce issue

1. Run `nativefier "https://beta.music.apple.com"`
2. Launch app
3. Click the blue "Sign In" button at the top right.

Results: New tab appears showing "ERROR_INSUFFICIENT_PARAMS"
Expected Results: New window opens to let you log into your Apple ID for Apple Music. 

### Details

- Are you nativefying a *public* website? 
Yes

- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? I don't know

- Full nativefier command used to build your app: `nativefier "https://beta.music.apple.com"`

- Version of Nativefier (run `nativefier --version`): `7.7.0`
- Version of node.js (run `node --version`): `v12.5.0`
- OS: `macOS 10.14.6>`
- Error message / stack trace (if any): ERROR_INSUFFICIENT_PARAMS

```
<Error message / Stack trace here>
```

**Comment by mxdpeep** [comment] 2019-09-07 14:42
yeah, it ends here:

 https://buy.itunes.apple.com/commerce/account/authenticateMusicKitRequest

**Comment by eshcheglov** [comment] 2019-09-18 18:37
Same here. By the way, if you press "Sign In" fast enough right after application open, login page appears and even allow you to login. 

But pushing "Play" button leads to "Unknown Error" pop-up

**Comment by SlimShadyIAm** [comment] 2019-10-04 09:22
Same here. No able to log in at all.

**Comment by jimnorrisiv** [comment] 2019-11-22 16:40
Has anyone found a way around this yet?

**Comment by BananaManCJ** [comment] 2019-11-24 23:13
I am also having this problem. I tried to use the --internal-url params, but had no luck.

**Comment by jimnorrisiv** [comment] 2019-12-06 22:05
I found a workaround: If I log into Apple Music in Chrome and then open the Nativefier it works! Looks like the credentials get cached in Chrome.

**Comment by Moxie1776** [comment] 2019-12-07 19:37
It seems to be sending these through itmss which is coming up as 'no handler'. when looking up itmss it appears it is trying to send these requests through iTunes.

**Comment by NIXOYE** [comment] 2020-02-24 22:00
anyone find a solution to this?

**Comment by ryzokuken** [comment] 2020-03-08 07:22
Any idea what's wrong and how this could be fixed? I'd be happy to send a patch.

**Comment by flying-sausages** [comment] 2020-07-12 01:15
Looks like this is no longer an issue when using `music.apple.com` as the auth window is within the main application. I can log in with no problems.

![image](https://user-images.githubusercontent.com/23618693/87236797-73720200-c3e5-11ea-81bc-fce777e9a7c4.png)

Would still be nice to fix the underlying bug that was preventing this, but this will not be reproducible anymore I suppose.

**Comment by ronjouch** [comment] 2020-07-18 13:36
> Looks like this is no longer an issue when using `music.apple.com` as the auth window is within the main application. I can log in with no problems.
> 
> ![image](https://user-images.githubusercontent.com/23618693/87236797-73720200-c3e5-11ea-81bc-fce777e9a7c4.png)
> 
> Would still be nice to fix the underlying bug that was preventing this, but this will not be reproducible anymore I suppose.

Good to know, thanks. Closing.

**Closed by ronjouch** 2020-07-18 13:36 UTC
Labels: bug
