### ISSUE TITLE
Error: rcedit.exe failed with exit code 1. Fatal error: Unable to commit changes     at ChildProcess.<anonymous> (C:\Users\jebel\AppData\Roaming\npm\node_modules\nativefier\node_modules\rcedit\lib\rcedit.js:68:16)

### ISSUE THREAD

**Issue by jebeld17** [jiahaog/nativefier#803] opened 2019-05-07 14:08 UTC
### Description

`C:\WINDOWS\system32>nativefier --name "Syncthing" "http://127.0.0.1:8384"
  packaging [===============================                   ] 61%Packaging app for platform win32 x64 using electron v3.1.7
  packaging [====================================              ] 72%Error: rcedit.exe failed with exit code 1. Fatal error: Unable to commit changes
    at ChildProcess.<anonymous> (C:\Users\jebel\AppData\Roaming\npm\node_modules\nativefier\node_modules\rcedit\lib\rcedit.js:68:16)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  packaging [========================================          ] 79%`

### Steps to reproduce issue

Attempt to Nativefy a local IP address, such as 127.0.0.1:8384, (this one in particular is used by a local sync service called Syncthing also available on Github).

### Details

- Are you nativefying a *public* website? No
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? N/A
- Full nativefier command used to build your app: `nativefier --name "Syncthing" "http://127.0.0.1:8384"`
- Version of Nativefier (run `nativefier --version`): `v7.6.12
- Version of node.js (run `node --version`): `v10.15.0`
- OS: `Windows 10 May 2019 Feature Update`
- Error message / stack trace (if any):
`C:\WINDOWS\system32>nativefier --name "Syncthing" "http://127.0.0.1:8384"
  packaging [===============================                   ] 61%Packaging app for platform win32 x64 using electron v3.1.7
  packaging [====================================              ] 72%Error: rcedit.exe failed with exit code 1. Fatal error: Unable to commit changes
    at ChildProcess.<anonymous> (C:\Users\jebel\AppData\Roaming\npm\node_modules\nativefier\node_modules\rcedit\lib\rcedit.js:68:16)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  packaging [========================================          ] 79%`

**Comment by HarshitJn** [comment] 2019-08-02 11:14
Same error. Any progress in this?

**Comment by ronjouch** [comment] 2020-01-29 03:55
Closing as duplicate of https://github.com/jiahaog/nativefier/issues/501

**Closed by ronjouch** 2020-01-29 03:55 UTC
