### ISSUE TITLE
Secondary windows are closed when primary window navigates to another page

### ISSUE THREAD

**Issue by FelixII** [jiahaog/nativefier#497] opened 2017-11-30 13:28 UTC
### Description

I'm using nativefier for various web apps like JIRA and occasionally need to view multiple windows of the same app side by side. I open a second window with Command + Click. The second window works fine until I navigate to another page in the first window. This causes the second window to close instantly.

### Steps to reproduce issue

1. Create a new nativefier app with the command below (or use any other website)
2. Command + Click on a link to open a second window
3. Put both windows side by side
4. Verify that you can navigate in the second window without affecting the first window
5. Click on a link in the first window and watch the second window disappear

### Details

- Are you nativefying a *public* website? Yes
- Feature request? No
- Full nativefier command used to build your app: `nativefier https://www.nytimes.com`
- Version of Nativefier (run `nativefier --version`): `v7.5.4`
- Version of node.js (run `node --version`): `v6.11.0`
- OS: `macOS 10.13.1`

Note: This issue does not occur when I open a new window with right click => Open in new window. However, I've noticed that some web pages (like JIRA) don't load properly when using this method.

**Comment by ronjouch** [comment] 2017-11-30 14:07
Hi @Felixll, thanks for the feedback. Closing as duplicate of #439, feel free to discuss and follow up there.

**Closed by ronjouch** 2017-11-30 14:07 UTC
