### ISSUE TITLE
Built-in ad blocker

### ISSUE THREAD

**Issue by AlfredEVOL** [jiahaog/nativefier#1062] opened 2020-10-31 22:59 UTC
It would be really good if there was a built-in ad blocker...

I usually watch youtube in brave..and its ad blocks by default is great...
but ads started to show in the nativefier app....

**Comment by ronjouch** [comment] 2020-10-31 23:26
Thanks @AlfredEVOL . Closing as duplicate of https://github.com/jiahaog/nativefier/issues/177

**Closed by ronjouch** 2020-10-31 23:26 UTC
Labels: feature-request
