### ISSUE TITLE
How do I call the standard print function?

### ISSUE THREAD

**Issue by nickbe** [jiahaog/nativefier#894] opened 2020-01-20 12:03 UTC
After creating a virtual desktop app from a website I can't find any way to print something.
Ctrl-P doesn't work. And there's not menu entry for printing.
Can anyone help me out here?

**Comment by zulfirman** [comment] 2020-01-23 09:22
Use this plugin, simple and effective..

https://jasonday.github.io/printThis/

**Comment by ronjouch** [comment] 2020-01-29 03:50
Closing as duplicate of https://github.com/jiahaog/nativefier/issues/504

**Closed by ronjouch** 2020-01-29 03:50 UTC
Labels: feature request
