### ISSUE TITLE
Functionality to pop-up for download location for each download like chrome/firefox

### ISSUE THREAD

**Issue by Manish-Pathak** [jiahaog/nativefier#920] opened 2020-03-10 12:33 UTC
Is it possible to add Functionality to have pop-up for download location for each download like chrome/firefox

**Comment by ronjouch** [comment] 2020-03-10 12:38
Thanks for the feedback. Downloads in nativefier suck, yup. Closing as duplicate of https://github.com/jiahaog/nativefier/issues/335 .

**Closed by ronjouch** 2020-03-10 12:38 UTC
