### ISSUE TITLE
Support building to package/snap/flatpak/appimage

### ISSUE THREAD

**Issue by JLIT0** [jiahaog/nativefier#512] opened 2017-12-15 17:42 UTC
Is there any possibility of the project generating Electron source code in the future that could be built with `electron-builder`?

The reason is that I would like to create packages for aarch64 and also snap files for Linux.

**Comment by ronjouch** [comment] 2018-01-03 17:29
@JLIT0 not now, no, but contributions welcome 🙂.

**Comment by ronjouch** [comment] 2020-03-18 04:56
Closing as duplicate of #249

**Closed by ronjouch** 2020-03-18 04:56 UTC
Labels: feature request, help wanted
