### ISSUE TITLE
Support for dynamic nativefier apps

### ISSUE THREAD

**Issue by allo-** [jiahaog/nativefier#677] opened 2018-08-30 19:44 UTC
### Description

I would be nice to use nativefier not only to generate an app-directory (which is about 100 MB per app with almost the same things in it for all apps), but to use command line options to define the app.

This would mean, that one dynamic app is built and then contains i.e. a ``nativefier`` binary, which is started with ``nativefier --name "appname" --url "https://website" --icon /path/to/icon``. This way you could create a lot of apps just by creating shortcuts with the correct parameters.

**Comment by ronjouch** [comment] 2018-10-11 01:34
Closing as duplicate of https://github.com/jiahaog/nativefier/issues/348

**Closed by ronjouch** 2018-10-11 01:34 UTC
