### ISSUE TITLE
The application doesn't load and the background remains white

### ISSUE THREAD

**Issue by david-pacheco** [jiahaog/nativefier#382] opened 2017-06-06 10:46 UTC
### Description

Randomly the application doesn't load and the background remains just white. 

### Steps to Reproduce Issue

There are no steps to reproduce. The issue happens randomly when the wrapper I created to my application running on localhost (127.0.0.1:XXXX) tries to load the page. If I access the application via the browser it always works with no problem, but sometimes the nativefier wrapper fails to load. If I close the nativefier app and re-open it sometimes it works, other times not...
Maybe problems with the cache ?

### Specifications
- Version of Nativefier: 7.3.1
- Version of Node.js: 6.9.1
- OS: Windows 10
- Architecture x64

**Comment by ronjouch** [comment] 2017-06-06 11:22
Hi @david-pacheco, thanks for the feedback.

- Could this be a duplicate of https://github.com/jiahaog/nativefier/issues/25 ?
- When this happens, please open the DevTools (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>). Any errors in `Console`? Any failing requests in `Network`?

At any rate, please come back with any information that may help understand the problem.

**Comment by david-pacheco** [comment] 2017-06-06 16:05
@ronjouch did you get the PR right? #25 seems to be just some minor fixes for typos...
As for your second question I wasn't able to see it yet, but when I'm able to reproduce it again I will check it out!

**Comment by ronjouch** [comment] 2017-06-06 16:11
@david-pacheco whoopsie, indeed, I meant https://github.com/jiahaog/nativefier/issues/252 , not 25.

**Comment by david-pacheco** [comment] 2017-06-06 16:15
No problem. The issue description is quite similar, but in my case there is no issue with internet connection, because the app is running on a localhost server and I can access it with the browser without any problem.

**Comment by jaysherrer2** [comment] 2017-06-28 15:57
I'm having the same issue, and an error message. I think it's the same problem so I'm posting here, but please move to a separate thread if not the correct location for this.

Anyway, here's the response I'm seeing in dev tools:

Failed to parse SourceMap: https://tickledmedia.facebook.com/private/var/folders/fy/y4rhyqrj5_zdkh0dry…FC56008B7/d/Workplace.app/Contents/Resources/app/lib/static/preload.js.map

**Comment by ronjouch** [comment] 2017-10-06 14:17
Closing as I can't reproduce the issue and there isn't much I can do. Feel free to chime in with more info, especially a reproduction scenario on a public website would help.

**Closed by ronjouch** 2017-10-06 14:17 UTC
Labels: bug, cannot reproduce, need info
