### ISSUE TITLE
What is the future plan for widevine issue?

### ISSUE THREAD

**Issue by terra9** [jiahaog/nativefier#1023] opened 2020-08-12 11:09 UTC
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [x] I searched existing issues, open & closed. Yes, my question is new.
- [x] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Comment by ronjouch** [comment] 2020-08-12 11:36
Closing as duplicate of https://github.com/jiahaog/nativefier/issues/435 , and quoting [recent releases](https://github.com/jiahaog/nativefier/releases),

> 👋 And a reminder: dear users / contributors! Public service announcement!
> 
> Nativefier is maintained by YOU. It's reasonably sane to hack on since
> the 8.x cleanup, it fits the use cases needed by the original author and
> the current maintainer, so _we_ are not doing any active development.
> 
> But it's not dead! If YOU use it and want to see juicy features & fixes,
> PR welcome! In particular, here are three particularly annoying issues;
> help welcome on those (or any other issue that motivates you 🙂):
> 
> - https://github.com/jiahaog/nativefier/issues/902
> - https://github.com/jiahaog/nativefier/issues/831
> - https://github.com/jiahaog/nativefier/issues/706
> - For other issues, https://github.com/jiahaog/nativefier/issues
> 
> Thanks! Take care.

**Closed by ronjouch** 2020-08-12 11:36 UTC
Labels: question
