### ISSUE TITLE
Support system-wide spell check on macOS

### ISSUE THREAD

**Issue by dsemaya** [jiahaog/nativefier#416] opened 2017-07-18 14:07 UTC
### Description
Please add support for system-wide spell check on macOS.  Chrome and Safari both support it, making it difficult to use sites like Gmail in Nativefier without spell check. 

### Steps to Reproduce Issue
Use Nativefier to make a Gmail app.
Compose an email and include spelling mistakes.    
No red line is shown.
Send embarrassing typos to your friends and colleagues.  Try to explain how your special version of Gmail doesn't have spell check because you used Nativefier.  

### Specifications
- Version of Nativefier 7.4.0
- Version of Node.jsv6.9.1
- OS: macOS 10.12.5
- Architecture x86
- Stack trace from the error message (if any)

**Comment by ronjouch** [comment] 2017-07-18 14:14
Closing as duplicate of #283

**Closed by ronjouch** 2017-07-18 14:14 UTC
