### ISSUE TITLE
Inject extension\application idea

### ISSUE THREAD

**Issue by rosolko** [jiahaog/nativefier#246] opened 2016-08-28 06:49 UTC
How do you this, is it possible to inject some extension\application to nativefier using [this](https://github.com/koush/electron-chrome) solution?

**Comment by aexmachina** [comment] 2016-09-07 04:26
There is a solution provided by Electron for this:

http://electron.atom.io/docs/tutorial/devtools-extension/

How would this be integrated into a Nativifier app?

**Comment by vrunjeti** [comment] 2016-09-12 08:10
@aexmachina That appears to be only for some of the dev tools' extensions. 

I was also hoping there would be a way to create Nativefier apps with chrome extensions built in, such as adblock

**Comment by ronjouch** [comment] 2017-04-08 03:29
Hey everyone, I see lots of directions here (the chrome apps polyfill, devtools-extensions, real chrome extensions) but no clear use cases. We're currently focusing on resuming maintenance of Nativefier and (maybe too aggressively) trimming our issues backlog, so I'm closing this issue, but feel free to come back with a more narrow use case (code even better :) ).

**Closed by ronjouch** 2017-04-08 03:29 UTC

**Comment by aubreypwd** [comment] 2017-07-25 15:53
Use Case:

I want to use Basecamp as a separate app (e.g. using Nativefier), but our team uses the Harvest Time Tracking extension (Chrome) which integrates with Basecamp. But, since I can't seem to package an extension with Nativefier, I can't get Basecamp _and_ the Harvest Time Tracking functionality together.

**Comment by ronjouch** [comment] 2017-07-25 16:28
@aubreypwd thanks for the feedback 👍. This issue ended up being a duplicate of https://github.com/jiahaog/nativefier/issues/207 , feel free to post your use case there.

**Comment by Rimseg** [comment] 2020-10-29 12:03
> There is a solution provided by Electron for this:
> 
> http://electron.atom.io/docs/tutorial/devtools-extension/
> 
> How would this be integrated into a Nativifier app?

Hello Simon,

let me show you one example of how i added this extension to my nativefier app:
https://chrome.google.com/webstore/detail/toggl-track-productivity/oejgccbfbmkkpaidnkphaiaecficdnfn

1. make a new chrome profile and add the extension of choice
2. get the folder the location should be something like `/home/user/.config/BraveSoftware/Brave-Browser/Profile X/Extensions/jfwieojrwneineiwjrowi/version_nr/`
in my example: 
`/home/nip/.config/BraveSoftware/Brave-Browser/Profile 7/Extensions/oejgccbfbmkkwerwerphaiaecficdnfn/1.66.10_0/`
3. add this line of code to your main.js of the nativefier app `nativefier_app/resources/app/lib/main.js`
```
const path = require('path')
const os = require('os')

BrowserWindow.addDevToolsExtension(
   path.join(os.homedir(), '/home/nip/.config/BraveSoftware/Brave-Browser/Profile 7/Extensions/oejgccbfbmkkwerwerphaiaecficdnfn/1.66.10_0/')
)
```


**NOTE**:
- if there is a login process, just do that in chrome 
- you can choose to isolate the plugin
- you have to change the code when it updates, if you choose to not isolate the plugin


for a more fleshed our version see: https://github.com/electron/electron/blob/master/docs/tutorial/devtools-extension.md
