### ISSUE TITLE
"WhatsApp works with Google Chrome 49+"

### ISSUE THREAD

**Issue by Kranzes** [jiahaog/nativefier#1000] opened 2020-07-04 21:26 UTC
3 days after making a WhatsApp web app i get this message and to fix it i have to delete the old app and remake a new one. i am not sure if this is something on my end or is this a bug with Nativefier but this thing has happened twice already to me.
![image](https://user-images.githubusercontent.com/56614642/86521180-1068f400-be56-11ea-9c0c-ddd260a8d4ca.png)

**Comment by sarweshparajuli** [comment] 2020-07-05 03:30
While nativefying `https://web.whatsapp.com` add `--honest` to the end of `nativefier --name "Whatsapp" "https://web.whatsapp.com"--internal-urls ".*.whatsapp.com.*" `  to make it `nativefier --name "Whatsapp" "https://web.whatsapp.com"--internal-urls ".*.whatsapp.com.*" --honest `. It will then work, by reporting Whatsapp the actual user agent which is Chrome.

Also, your Nativefier might not be up to date, so update it by typing `npm update -g nativefier` in CMD.

**Comment by Kranzes** [comment] 2020-07-06 13:44
that didnt fix my issue...

**Comment by sarweshparajuli** [comment] 2020-07-07 00:10
What is the command you used, along with your OS, Arch and Nativefier version.

**Comment by Kranzes** [comment] 2020-07-07 08:39
I used ``nativefier --name "Whatsapp" "https://web.whatsapp.com"--internal-urls ".*.whatsapp.com.*" --honest `` I'm running Fedora 32 and my Nativefier version is 9.0.0.

**Comment by ronjouch** [comment] 2020-07-18 05:51
Closing as duplicate of https://github.com/jiahaog/nativefier/issues/719 , see there for workarounds.

**Closed by ronjouch** 2020-07-18 05:51 UTC
