### ISSUE TITLE
File download progress and status 

### ISSUE THREAD

**Issue by maheshprabhu2010** [jiahaog/nativefier#395] opened 2017-06-30 13:39 UTC
### Description
When I download any file from my application, Nativefiered application interface not showing any download status. It would be better to add download progress and status of downloads.

### Specifications
Version of Nativefier (run $ nativefier --version): v7.4.0
Version of Node.js (run $ node --version): v6.10.3
OS: Windows 10
Architecture 64 Bit

- Stack trace from the error message (if any)

**Comment by ronjouch** [comment] 2017-07-04 01:48
Closing as duplicate of https://github.com/jiahaog/nativefier/issues/335

**Closed by ronjouch** 2017-07-04 01:48 UTC
