### ISSUE TITLE
Using Nativefier to wrap a local file/folder

### ISSUE THREAD

**Issue by samirotiv** [jiahaog/nativefier#243] opened 2016-08-24 11:29 UTC
Hi,
I'm sorry I am posting an issue for this instead of figuring it out myself, but I couldn't find any immediate documentation, and I'm new to NodeJS, and also am in a bit of a hurry.

Cutting to the question - instead of a website, like "http://google.com", I would like to wrap my web application into a native Windows app. It has a folder structure, with an index file that needs to be accessed and opened. How do I do this?

On another note, it would also need to enable cross origin requests.

I would greatly appreciate if anybody could point me to what I could do.

Thanks very much!

**Comment by Silent-Hunter** [comment] 2016-08-24 21:46
I too wish to do this, pretty much the exact same situation here.

**Comment by andresgottlieb** [comment] 2016-08-25 20:42
@samirotiv and @Silent-Hunter , you could use http://electron.atom.io/

**Comment by ronjouch** [comment] 2017-04-08 04:55
Duplicate of https://github.com/jiahaog/nativefier/issues/45 , closing this one.

**Closed by ronjouch** 2017-04-08 04:55 UTC
Labels: feature request
