### ISSUE TITLE
Packaging hangs at 80%

### ISSUE THREAD

**Issue by the4ndy** [jiahaog/nativefier#362] opened 2017-05-12 14:28 UTC
### Description
hangs at 80% when trying to build an app from file.pizza

### Steps to Reproduce Issue
install nativefier globally `npm install -g nativefier`
run `nativefier "file.pizza"

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.3.1`
- Version of Node.js (run `$ node --version`): `v6.10.2`
- OS: `Windows 10`
- Architecture `x64`
- Stack trace from the error message (if any)

```
<Stack trace here>
```

**Comment by ronjouch** [comment] 2017-05-14 01:29
@the4ndy thanks for the feedback! Couldn't reproduce the issue, though, under Windows 10, Node 6.10.2, Nativefier 7.3.1.

We do a bad job at showing to users what the current task is, and *"at 80%"* doesn't help isolate what's borked. I suspect the icon/name inferring is failing, can you try the `--icon` and `--name` options and report back? For example, save [an icon for file.pizza as filepizza.png](https://encrypted.google.com/search?hl=en&q=filepizza&tbm=isch&tbs=ift:png) in the current terminal folder and run:

```
nativefier --name filepizza --icon filepizza.png "https://file.pizza"
```

**Comment by ronjouch** [comment] 2017-05-21 13:18
Closing as issue wasn't reproducible and didn't get feedback. @the4ndy feel free to chime in and re-open the discussion anytime 🙂!

**Closed by ronjouch** 2017-05-21 13:18 UTC
Labels: bug, need info

**Comment by theodoreroddy** [comment] 2018-06-20 19:34
@ronjouch I'm having this same issue. Here's a screenshot:

![capture](https://user-images.githubusercontent.com/13633257/41680402-019d986e-7497-11e8-8e8a-9312d3ae109e.PNG)

**Comment by theodoreroddy** [comment] 2018-06-20 19:42
@ronjouch @the4ndy Actually, I figured it out. Windows Defender is blocking node from writing the file. To fix this, go to **Windows Defender Security Center**. Then go to **Virus & threat protection settings**. Scroll down to **Controlled folder access**, click **Manage Controlled Folder access**. Click **Allow an app through Controlled folder access**. Add **C:\Program Files\nodejs\node.exe** or whatever the path is to your node.exe.

**Comment by amelberger** [comment] 2019-02-26 10:12
> 
> 
> @ronjouch @the4ndy Actually, I figured it out. Windows Defender is blocking node from writing the file. To fix this, go to **Windows Defender Security Center**. Then go to **Virus & threat protection settings**. Scroll down to **Controlled folder access**, click **Manage Controlled Folder access**. Click **Allow an app through Controlled folder access**. Add **C:\Program Files\nodejs\node.exe** or whatever the path is to your node.exe.
> 
> I also needed to add C:\Users\you\AppData\Roaming\npm\node_modules\nativefier\node_modules\rcedit\bin\rcedit.exe

am having the same issue still, although I did exactly what you said. Did you do anything else or was adding these two .exe enough?

**Comment by royandika** [comment] 2019-03-26 10:59
I am have the same issue here, stopped at 68-75% packaging averytime for any website, i've shutdowned my windows defender/antivirus too, but not worked. Any suggestion to fix it?
![nativefier-stopped](https://user-images.githubusercontent.com/7483898/54992050-dec97200-4ff0-11e9-886b-b1a85211e4b8.jpg)
