### ISSUE TITLE
WhatsApp not detecting the browser version

### ISSUE THREAD

**Issue by jjolmo** [jiahaog/nativefier#959] opened 2020-04-27 09:19 UTC
Since two days or so I noticed that a Whatsapp application made in nativefier stops detecting the browser version upon the second or third run. It creates the app correctly but then it shows this:
![image](https://user-images.githubusercontent.com/43957544/80353495-bbb56580-8875-11ea-916e-74ef43aa5da4.png)

To note
- [] I'm using the last version of nativefier
- [] Fedora 31 with KDE

I followed these steps:
- [] Created an app with this chain:
`nativefier -p linux --icon ~/.local/share/applications/notion.png --name "Whatsapp" -a x64 https://web.whatsapp.com --disable-dev-tools --single-instance --tray`
- [] Used correctly for a day
- [] Next day, Whatsapp no longer detects the browser identification

It worked flawlessy some days ago.

**Expected behavior**
Whatsapp should detect chromium version and run correcly

**Actual behavior**
Whatsapp shows that the browser should be at least chromium 49+

**Debug info**
```
[11:17:07] cidwel@localhost [WhatsAppWeb-linux-x64] $ ./WhatsAppWeb 
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
```
**Context**
 - Nativefier: 8.0.4
 - Node.js: 12.14.1
 - Npm: 6.13.4
 - OS: Fedora 31 KDE
 - Is it a regression? no (I updated it to 8.0.4 to see if that fixed the issue)

many thanks!

**Comment by ronjouch** [comment] 2020-04-27 13:20
Closing as duplicate of https://github.com/jiahaog/nativefier/issues/719

**Closed by ronjouch** 2020-04-27 13:20 UTC
Labels: bug

**Comment by bobbinyolk** [comment] 2020-04-27 13:25
This is most certainly not a duplicate. Between 719 and now whatsapp has been working. At the moment I use the workaround of 719, and that works, but is not a solution
