### ISSUE TITLE
Build fails when using both options --conceal and --icon

### ISSUE THREAD

**Issue by williamtan89** [jiahaog/nativefier#284] opened 2016-11-04 08:17 UTC
### Description
Trying to generate a new app with --icon and --conceal, received error. icon not being used in the desktop app.

### Steps to Reproduce Issue
Just include --conceal together with --icon pointing to a correct image location.

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v1.4.5`
- Version of Node.js (run `$ node --version`): `v6.9.1`
- OS: `Windows`
- Architecture `default`

```
[ { Error: ENOENT: no such file or directory, open 'C:\Users\user\Desktop\nativefier\appname\resources\app\icon.png'
      at Error (native)
    errno: -4058,
    code: 'ENOENT',
    syscall: 'open',
    path: 'C:\\Users\\user\\Desktop\\nativefier\\appname\\resources\\app\\icon.png' } ]
```

**Comment by oller** [comment] 2017-02-02 17:58
+1 for this error.

If you try a relative icon path, such `./icon/icon.png` it'll resolve from the dest folder, not the source, so if you try and account for this with `../../../icon/icon.png` for example, it'll then start resolving from the source!

Looks like it just can't handle paths correctly for the `--icon` option?

**Comment by ronjouch** [comment] 2017-04-08 05:17
Duplicate of https://github.com/jiahaog/nativefier/issues/233, closing this one.

**Closed by ronjouch** 2017-04-08 05:17 UTC
Labels: bug
