### ISSUE TITLE
🐞 Apps that open multiple tabs throw an error when closing one.

### ISSUE THREAD

**Issue by altechzilla** [jiahaog/nativefier#1040] opened 2020-09-01 06:24 UTC
**Homework**

- [X] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [X] I searched existing issues, open & closed. Yes, my bug is new.
- [X] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Bug description**

**Steps to reproduce**

```
const nativefier = require("nativefier").default;
const fs = require("fs");
const path = require("path");
const apps = JSON.parse(fs.readFileSync("./apps.json"));
const defaultInject = ["./source/css/styles.css"];

/**
 * Render App
 *
 * @param {*} app
 */

function renderApp(app) {
  return new Promise(function (resolve, reject) {
    nativefier(
      {
        name: app.name,
        targetUrl: app.url,
        dest: "./build/" + app.name + "/",
        appCopyright: "Annonymous",
        appVersion: "1.0.0",
        counter: true,
        bounce: true,
        width: 1600,
        height: 1000,
        showMenuBar: false,
        ignoreCertificate: false,
        ignoreGpuBlacklist: false,
        enableEs3Apis: false,
        insecure: false,
        internalUrls: ".*?." + app.pattern + "/.*?",
        hideWindowFrame: true,
        titleBarStyle: "hiddenInset",
        disableDevTools: false,
        disableContextMenu: true,
        singleInstance: true,
        clearCache: false,
        // tray: "stay-in-tray",
        darwinDarkModeSupport: true,
        platform: "darwin",
        arch: "x64",
        version: "1.0.0",
        out: "./build",
        overwrite: true,
        inject: app.inject ? [...defaultInject, ...app.inject] : defaultInject,
        asar: false,
        icon: "./source/img/" + app.name + ".png",
        fastQuit: false,
        userAgent:
          "Mozilla/5.0 (Windows NT 10.0; rv:74.0) Gecko/20100101 Firefox/74.0",
        honest: false,
        zoom: 1.0,
        win32metadata: {
          CompanyName: app.name,
          FileDescription: app.name + " Desktop App",
          OriginalFilename: app.name,
          ProductName: app.name,
          InternalName: app.name,
        },
      },
      function (error, appPath) {
        if (error) {
          reject(error);
        } else {
          resolve(app.name + " has been nativefied to", appPath);
        }
      }
    );
  }).catch((error) => console.error(error));
}

/**
 * Render Apps
 */

(async function renderApps() {
  for (const app of apps) {
    await renderApp(app);
  }
})();

```

**Expected behavior**

No error when closing a tab.

**Actual behavior**

An error pops up all the time for every app.

**Debug info**

<img width="267" alt="image" src="https://user-images.githubusercontent.com/8274669/91806056-63271800-ec1b-11ea-956a-b67ce3c6c4e3.png">

**Context**

 - Nativefier: 9.1.0
 - Node.js: v12.18.3
 - Npm: 6.14.7
 - OS: macOS
 - Is it a regression? It's been happening for all versions I think.
 - Additional context: n/a

**Comment by ronjouch** [comment] 2020-09-03 02:42
Closing as duplicate of https://github.com/jiahaog/nativefier/issues/939

**Closed by ronjouch** 2020-09-03 02:42 UTC
Labels: bug
