### ISSUE TITLE
macOS No Icons

### ISSUE THREAD

**Issue by Raziel2244** [jiahaog/nativefier#555] opened 2018-03-14 16:38 UTC
### Description

No icons for messenger.com app or web.whatsapp.com app on macOS High Sierra 10.13 Beta 4. ImageMagick is in path and Xcode is installed.

### Steps to reproduce issue

Ran 'nativefier [address]' and later 'nativefier --name [name] [address]' for each of them but got no icons for the apps.

### Details

- Are you nativefying a *public* website? Yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? N/A
- Full nativefier command used to build your app: `nativefier [address]` and `nativefier --name [name] [address]`
- Version of Nativefier (run `nativefier --version`): `v7.5.4`
- Version of node.js (run `node --version`): `v9.8.0`
- OS: `macOS 10.13 Beta 4`
- Error message / stack trace (if any):

```
N/A
```

**Comment by ronjouch** [comment] 2018-03-14 17:06
@Raziel2244 thanks for the feedback. Known issue, closing as duplicate of https://github.com/jiahaog/nativefier/issues/529 . For now just download a PNG icon locally (e.g. to `/tmp/icongmail.png`) and nativefy explicitly with `--icon /tmp/icongmail.png`

**Closed by ronjouch** 2018-03-14 17:06 UTC
