### ISSUE TITLE
saveAs option seems doesn't work

### ISSUE THREAD

**Issue by sindzicat** [jiahaog/nativefier#563] opened 2018-03-26 09:46 UTC
### Description

I can't make my app to show save As dialog.

### Steps to reproduce issue

Try to download any attachement. File will be downloaded to default folder `%USERPROFILE%\Download`. You will not see save As window.

### Details

- :heavy_check_mark: Are you nativefying a *public* website? **yes** `https://mail.yandex.ru`
- :heavy_multiplication_x: Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? **no, it's not a feature request**
- :heavy_check_mark: Full nativefier command used to build your app:
```
nativefier --name YandexMail --icon "E:\\path\to\yandex-mail.png" --counter --maximize   https://mail.yandex.ru --zoom 1.2 --tray --file-download-options "{\"saveAs\": true}" "C:\\path\to\YandexMail"
```
- :heavy_check_mark: Version of Nativefier (run `nativefier --version`): **v7.5.4**
- :heavy_check_mark: Version of node.js (run `node --version`): **v9.8.0**
- :heavy_check_mark: OS: **Windows 7x64**
- :heavy_multiplication_x: Error message / stack trace (if any): **no error message**

```
<Error message / Stack trace here>
```

**Comment by ronjouch** [comment] 2018-03-26 12:28
@sindzicat thanks for the feedback. Known issue, closing as duplicate of #335. See discussion up there.

**Closed by ronjouch** 2018-03-26 12:28 UTC
