### ISSUE TITLE
WhatsApp Web not working

### ISSUE THREAD

**Issue by firefinchdev** [jiahaog/nativefier#1031] opened 2020-08-25 11:50 UTC
**Homework**

- [ X] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [ X] I searched existing issues, open & closed. Yes, my bug is new.
- [ X] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Bug description**

Use nativefier for web.whatsapp.com
The generated app works for first time, but next time (on opening the app), it shows the following message (see screeenshot).

**Steps to reproduce**
1. 
```
nativefier "web.whatsapp.com"
```
2. Open generated app
3. Login using Qr (Optional step, I think)
4. Close the app after 10-15 seconds
5. Reopen the app
6. The following screenshot appears.

**Expected behavior**

Able to access web.whatsapp.com

**Actual behavior**

Refer screenshot.

**Debug info**
The chrome version reported by the electron app is 83, which satisfies the minimum requirement as per screenshot.
The problem happens because:
1. Launch app 1st time: web.whatsapp.com loads a service worker along with the whatsapp web app.
2. service worker is loaded into the app.
3. Close the app.
4. Reopen the app: This time web.whatsapp.com document is loaded by service worker (not by direct request to the server). This service worker is somehow responsible for the screenshot message.
5. Temporary fix: View -> Dev tools -> Application -> Service workers -> unregister. Now reload the page (View -> Reload). This, however, is not ideal solution because we enter a loop here (starting again with step 1).
<img width="1648" alt="Screenshot 2020-08-25 at 5 08 32 PM" src="https://user-images.githubusercontent.com/26357501/91170336-5d4ea580-e6f6-11ea-9adf-71f4f707d327.png">

**Context**

 - Nativefier: (for example: 9.2.0)
 - Node.js: (for example: 14.6.0)
 - Npm: (for example: 6.14.7)
 - OS: (for example: macOS 10.15.6)
 - Is it a regression? No

**Comment by ronjouch** [comment] 2020-08-25 12:20
Closing as duplicate of https://github.com/jiahaog/nativefier/issues/719 , see there for workarounds.

**Closed by ronjouch** 2020-08-25 12:20 UTC
Labels: bug
