### ISSUE TITLE
You'll need a new app to open this about

### ISSUE THREAD

**Issue by IsaacAbrahamson** [jiahaog/nativefier#533] opened 2018-02-05 18:25 UTC
### Description

First off, I love this tool--it works great! I'm getting an annoying issue making a certain website. Every time I open the app, Windows gives me this stupid dialog box:

![image](https://image.prntscr.com/image/gRfQ3Cf0Saq2m4tfThIr1A.png)

### Steps to reproduce issue
```bash
$ nativefier "https://textfree.us/" --inject "C:\pathToFile\inject.css" --icon "C:\pathToFile\icon.png" --name TextFree
```

### Details
- My injected stylesheet simply hides ads
- It happens every time I create this website regardless if I add the extra options or not.
- Other websites I've tried work like expected and don't bring this up.
- I can press `esc` to get rid of dialog, but it's annoying anyway.

---

> Are you nativefying a *public* website?

Yes

> Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?

No

> Full nativefier command used to build your app: `<command here>`

Above

> Version of Nativefier (run `nativefier --version`): `v0.0.0`

7.5.4

> Version of node.js (run `node --version`): `v0.0.0`

9.4.0

> OS: `<OS here>`

Windows 10

> Error message / stack trace (if any):

none

**Comment by ronjouch** [comment] 2018-05-17 01:04
Closing as duplicate of https://github.com/jiahaog/nativefier/issues/562

**Closed by ronjouch** 2018-05-17 01:04 UTC
