### ISSUE TITLE
[WINDOWS]Not a smooth transition between the navigation. 

### ISSUE THREAD

**Issue by Armand1965** [jiahaog/nativefier#782] opened 2019-04-04 11:55 UTC
### Description

I published an app by nativefier. When I open the app, if I click the button links to open another page, there is not a smooth transition between the navigation. It takes time to render the page in half a second, but enough to show a white space between
  the transition to display the rendered screen. How to solve this?
The CSS settings on the page are appropriate.

### Steps to reproduce issue
nativefier "caminho da aplicação"

### Details

- Are you nativefying a *public* website?
No: It,'s a localhost adress
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
Yes and I don't localizated nothing about that...
- Full nativefier command used to build your app: 
nativefier "http://localhost/Ecras/Patriarcados/Encarnacao/index.html
- Version of Nativefier (run `nativefier --version`): 
nativefier 7.6.12
- Version of node.js (run `node --version`): `v10.15.1`
- OS: `Windows 10'

**Comment by ronjouch** [comment] 2019-04-19 17:33
Closing as duplicate of #183

**Closed by ronjouch** 2019-04-19 17:33 UTC

**Comment by Armand1965** [comment] 2019-04-23 09:25
They closed my problem without giving me a solution, attaching it to a previously reported bug.
I need to know if there is a solution to this problem. See the closed ticket # 782
If you read the answers to problem # 183, you will see that there was no solution, only other reports with the same problem.
Do you have a solution or a way to identify what to do to stop the white screen between pages?
