### ISSUE TITLE
no picture in youtube video

### ISSUE THREAD

**Issue by denegny** [jiahaog/nativefier#307] opened 2017-01-03 07:19 UTC
### Description
Dont show picture in youtube video frame
![screenshot-area-2017-01-03-091754](https://cloud.githubusercontent.com/assets/3710958/21601701/b0c77b58-d195-11e6-8dd5-68120538101b.png)

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `7.0.1`
- Version of Node.js (run `$ node --version`): `v4.2.6`
- OS: `LinuxMint 4.4.0-57-generic`
- Architecture `x86_64`
- Stack trace from the error message (if any)

```
<Stack trace here>
```

**Comment by ronjouch** [comment] 2017-04-07 17:22
Hi @denegny, thanks for the bug report. Sadly I cannot reproduce the issue on my machine :-/ .

- Can you try with the latest Nativefier 7.1.0 and a recent electron? Use nativefier's `--electron-version` (full help available at `nativefier --help`)
- Do videos play fine in Chrome?
- If still not working, can you precise the issue scenario a bit more? Was the app youtube.com, or was the video frame an iframe embed?

**Comment by ronjouch** [comment] 2017-04-21 01:35
Closing as issue wasn't reproducible and didn't get feedback. @denegny feel free to chime in (we just released Nativefier 7.2.0 with an upgraded default Electron, which may be helpful in your case) and re-open the discussion anytime 😃!

**Closed by ronjouch** 2017-04-21 01:35 UTC
Labels: bug, cannot reproduce
