### ISSUE TITLE
Open Mailto links in nativefied Inbox/Gmail

### ISSUE THREAD

**Issue by nikjft** [jiahaog/nativefier#679] opened 2018-09-06 19:34 UTC
### Description

I want to be able to open mailto URLs in my Inbox and/or Gmail browser.

### Steps to reproduce issue

Sent terminal command: open -a 'Google Inbox.app' 'mailto://test@nowhere.nu'

Expected result: Open compose window

Actual result: app comes to front, nothing else happens

### Details

Creation string:

nativefier --counter -i /Users/nik/Desktop/inbox.png --internal-urls ".*inbox\.google\.com.*|^mailto:.*" --single-instance -n "Google Inbox" --inject "/Users/nik/Desktop/ginbox-inject.js" "https://inbox.google.com/"

Running on MacOS X.

**Comment by ronjouch** [comment] 2018-10-11 01:43
@nikjft thanks for the feedback. Closing as duplicate of https://github.com/jiahaog/nativefier/issues/405

**Closed by ronjouch** 2018-10-11 01:43 UTC
