### ISSUE TITLE
Add download confirmation whenever a file is downloaded from a site

### ISSUE THREAD

**Issue by Finermeerkat137** [jiahaog/nativefier#935] opened 2020-03-28 18:51 UTC
**Problem statement**
Whenever I download a file from a site, there is no confirmation that I downloaded. Many times I've clicked a file download linkmultiple times, not knowing if it downloaded or not, and went into my downloads folder, and there were 4 or 5 copies of the file.

**Suggested solution**
There should be a confirmation like in Google Chrome where it tells you that the file has been downloaded. It shows up in the bottom of the windows maybe, or a notification comes up saying the file is downloading.

**Comment by ronjouch** [comment] 2020-03-28 19:02
Closing as duplicate of https://github.com/jiahaog/nativefier/issues/335

**Closed by ronjouch** 2020-03-28 19:02 UTC
