### ISSUE TITLE
[Electron 7.0.1 regression] Evernote white/blank page after logging in, and cookie errors in console

### ISSUE THREAD

**Issue by 4l1fe** [jiahaog/nativefier#926] opened 2020-03-19 14:00 UTC
**Bug description**
i get a blank page after logging in.

**Steps to reproduce**
1. [command and output](https://gist.github.com/4l1fe/6d475dfa0829ca51b803ec7eac0f36ab)
2. change the permission owner and group of a target folder to my current user

**Expected behavior**
Ordinary page load after logging in

**Actual behavior**
Blank page

**Logs & screenshots**
there are 12 errors In a dev tool console as follow
```
Thu Mar 19 20:32:49 GMT+700 2020 com.google.gwt.logging.client.LogConfiguration
SEVERE: Error: Invalid cookie value: 
java.lang.JsException: Error: Invalid cookie value: 
	at Unknown.value(https://www.evernote.com/ro/L2RkMDZkYTE2Y2FmYmQxNjMxYWIwZTMwMTIxMmFkNWY4MDE3NTgwMWEuanM/L2UxNTRhNzRiNWEyZWY0MGIzNWI5NWFlYzJlYWU4NmJjYWQ1NmQzY2EuanM/-1248196736.js)
	at Unknown.value(https://www.evernote.com/ro/L2RkMDZkYTE2Y2FmYmQxNjMxYWIwZTMwMTIxMmFkNWY4MDE3NTgwMWEuanM/L2UxNTRhNzRiNWEyZWY0MGIzNWI5NWFlYzJlYWU4NmJjYWQ1NmQzY2EuanM/-1248196736.js)
	at Unknown._getCsrfBusterTokenFromCookie(https://www.evernote.com/ro/L2RkMDZkYTE2Y2FmYmQxNjMxYWIwZTMwMTIxMmFkNWY4MDE3NTgwMWEuanM/L2UxNTRhNzRiNWEyZWY0MGIzNWI5NWFlYzJlYWU4NmJjYWQ1NmQzY2EuanM/-1248196736.js)
	at Unknown._refreshCsrfBusterTokenMaybe(https://www.evernote.com/ro/L2RkMDZkYTE2Y2FmYmQxNjMxYWIwZTMwMTIxMmFkNWY4MDE3NTgwMWEuanM/L2UxNTRhNzRiNWEyZWY0MGIzNWI5NWFlYzJlYWU4NmJjYWQ1NmQzY2EuanM/-1248196736.js)
	at Unknown.getCsrfBusterToken(https://www.evernote.com/ro/L2RkMDZkYTE2Y2FmYmQxNjMxYWIwZTMwMTIxMmFkNWY4MDE3NTgwMWEuanM/L2UxNTRhNzRiNWEyZWY0MGIzNWI5NWFlYzJlYWU4NmJjYWQ1NmQzY2EuanM/-1248196736.js)
	at Unknown.$Wd(<anonymous>)
	at Unknown.UWd(<anonymous>)
	at Unknown.WWd(<anonymous>)
	at Unknown.hRb(<anonymous>)
	at Unknown.TPb(<anonymous>)
	at Unknown.fQb(<anonymous>)
	at Unknown.anonymous(<anonymous>)
	at Unknown.execCb(https://www.evernote.com/ro/L2RjOWVmYTJkNzQ5ODlhNGIxZWNjNjY2NTk3NDdjOGE3NDIwMmRjY2MuanM/L2RjYzUxZWE5ZGUzN2UzYTgwOTliMmMwYWE5Zjg3MGViNGQzNGIwYzYuanM/LzZhNWE1ZjQ4ZjNiNDVkY2YzNzc5ODc1Mzk2MDU5YWM5MWI4NmMyOTYuanM/LzEwNTU4ZDNlYjgyYWVhMWUxNDBkNWYxNWMwMzQ2ZWVmMzk1MzY2MGQuanM/L2JjYjllOTZiOWIxYmQ5NmI5MmE5YWI3MjA4NDA5NGZiOTk0NWM0NDQuanM/LzZjNTdhOTU4YWUzNjkwOGJjYjM1MGQ0MmM2YmZhMGUyMDliYzIwYTQuanM/-1768367214.js)
	at Unknown.check(https://www.evernote.com/ro/L2RjOWVmYTJkNzQ5ODlhNGIxZWNjNjY2NTk3NDdjOGE3NDIwMmRjY2MuanM/L2RjYzUxZWE5ZGUzN2UzYTgwOTliMmMwYWE5Zjg3MGViNGQzNGIwYzYuanM/LzZhNWE1ZjQ4ZjNiNDVkY2YzNzc5ODc1Mzk2MDU5YWM5MWI4NmMyOTYuanM/LzEwNTU4ZDNlYjgyYWVhMWUxNDBkNWYxNWMwMzQ2ZWVmMzk1MzY2MGQuanM/L2JjYjllOTZiOWIxYmQ5NmI5MmE5YWI3MjA4NDA5NGZiOTk0NWM0NDQuanM/LzZjNTdhOTU4YWUzNjkwOGJjYjM1MGQ0MmM2YmZhMGUyMDliYzIwYTQuanM/-1768367214.js)
	at Unknown.enable(https://www.evernote.com/ro/L2RjOWVmYTJkNzQ5ODlhNGIxZWNjNjY2NTk3NDdjOGE3NDIwMmRjY2MuanM/L2RjYzUxZWE5ZGUzN2UzYTgwOTliMmMwYWE5Zjg3MGViNGQzNGIwYzYuanM/LzZhNWE1ZjQ4ZjNiNDVkY2YzNzc5ODc1Mzk2MDU5YWM5MWI4NmMyOTYuanM/LzEwNTU4ZDNlYjgyYWVhMWUxNDBkNWYxNWMwMzQ2ZWVmMzk1MzY2MGQuanM/L2JjYjllOTZiOWIxYmQ5NmI5MmE5YWI3MjA4NDA5NGZiOTk0NWM0NDQuanM/LzZjNTdhOTU4YWUzNjkwOGJjYjM1MGQ0MmM2YmZhMGUyMDliYzIwYTQuanM/-1768367214.js)
	at Unknown.init(https://www.evernote.com/ro/L2RjOWVmYTJkNzQ5ODlhNGIxZWNjNjY2NTk3NDdjOGE3NDIwMmRjY2MuanM/L2RjYzUxZWE5ZGUzN2UzYTgwOTliMmMwYWE5Zjg3MGViNGQzNGIwYzYuanM/LzZhNWE1ZjQ4ZjNiNDVkY2YzNzc5ODc1Mzk2MDU5YWM5MWI4NmMyOTYuanM/LzEwNTU4ZDNlYjgyYWVhMWUxNDBkNWYxNWMwMzQ2ZWVmMzk1MzY2MGQuanM/L2JjYjllOTZiOWIxYmQ5NmI5MmE5YWI3MjA4NDA5NGZiOTk0NWM0NDQuanM/LzZjNTdhOTU4YWUzNjkwOGJjYjM1MGQ0MmM2YmZhMGUyMDliYzIwYTQuanM/-1768367214.js)
	at Unknown.anonymous(https://www.evernote.com/ro/L2RjOWVmYTJkNzQ5ODlhNGIxZWNjNjY2NTk3NDdjOGE3NDIwMmRjY2MuanM/L2RjYzUxZWE5ZGUzN2UzYTgwOTliMmMwYWE5Zjg3MGViNGQzNGIwYzYuanM/LzZhNWE1ZjQ4ZjNiNDVkY2YzNzc5ODc1Mzk2MDU5YWM5MWI4NmMyOTYuanM/LzEwNTU4ZDNlYjgyYWVhMWUxNDBkNWYxNWMwMzQ2ZWVmMzk1MzY2MGQuanM/L2JjYjllOTZiOWIxYmQ5NmI5MmE5YWI3MjA4NDA5NGZiOTk0NWM0NDQuanM/LzZjNTdhOTU4YWUzNjkwOGJjYjM1MGQ0MmM2YmZhMGUyMDliYzIwYTQuanM/-1768367214.js)
```

**Context**
 - Nativefier: 8.0.4
 - OS: Ubuntu 18.04.4

**Comment by ronjouch** [comment] 2020-03-19 14:38
Hi @4l1fe and thanks for the feedback.

1. Is this a regression in Nativefier 8.x ? Did the issue arise in 7.7.1, and with 7.7.1 passing flag `--electron-version 8.1.1` ?
2. Can you peek in both versions what the sent cookies look like, and report if you see obvious glitches/corruption?

**Comment by 4l1fe** [comment] 2020-03-19 18:45
> Hi @4l1fe and thanks for the feedback.
> 
> 1. Is this a regression in Nativefier 8.x ? Did the issue arise in 7.7.1, and with 7.7.1 passing flag `--electron-version 8.1.1` ?
> 2. Can you peek in both versions what the sent cookies look like, and report if you see obvious glitches/corruption?

1. Nativefier7.7.1 is working ok. Nativefier7.7.1-8.1.1 isn't working
2. Haven't seen a difference. All sent cookie names are same.

**Comment by ronjouch** [comment] 2020-03-19 19:16
>     1. Nativefier7.7.1 is working ok. Nativefier7.7.1-8.1.1 isn't working

@4l1fe great, thanks for the feedback, so it's Electron trouble.

It would be super helpful if you could you bisect the exact version of Electron where things started failing. Keep re-building & testing your app in Nativefier 7.7.1 with lower versions of Electron until cookies work again. The default version of Electron used by Nativefier 7.7.1 is 5.0.13, so far we know the problem belongs in ( 5.0.13, 8.1.1 ), Electron releases are listed at https://github.com/electron/electron/releases , and you can bisect coarsely to begin with (going from major to major version). It's probably a documented change, so I'll expect we'll figure it out after you give the first broken major version.

**Comment by 4l1fe** [comment] 2020-03-20 16:29
So the last release doesn't have this problem is 6.1.9. Since the electron 7.0.1 version i see a blank page.

**Comment by ronjouch** [comment] 2020-03-20 16:38
> So the last release doesn't have this problem is 6.1.9. Since the electron 7.0.1 version i see a blank page.

@4l1fe thanks a ton for digging 🙂! Will look at it.

**Comment by ronjouch** [comment] 2020-03-21 13:48
After some digging, closing as duplicate of https://github.com/jiahaog/nativefier/issues/902 . See https://github.com/jiahaog/nativefier/issues/902#issuecomment-602043536 for details, and I'm asking for Electron help in https://github.com/electron/electron/issues/21256#issuecomment-602045272 .

**Closed by ronjouch** 2020-03-21 13:48 UTC
Labels: bug, help wanted

**Comment by ronjouch** [comment] 2020-03-21 13:59
@4l1fe until this is fixed or I get help in https://github.com/electron/electron/issues/21256#issuecomment-602045272 , passing `-e 6.1.9` should be a fine workaround. I'm considering reverting the default Electron to 6.1.9 too if I don't get any news.

**Comment by 4l1fe** [comment] 2020-03-24 16:13
great, thx. I'm waitng for news.
