### ISSUE TITLE
Mail print functionality not working on App (Mac OS Catalina). 

### ISSUE THREAD

**Issue by SridharArrabelly** [jiahaog/nativefier#872] opened 2019-10-23 12:54 UTC
### Description

email print functionality is not working. when I click print, popup doesn't come.

### Steps to reproduce the issue

1. Open email
2. click on more actions (...) 
3. select print - nothing happens.

### Details

- Are you nativefying a *public* website?
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- Full nativefier command used to build your app: `<command here>`
- Version of Nativefier (run `nativefier --version`): `v0.0.0`
- Version of node.js (run `node --version`): `v0.0.0`
- OS: `<OS here>`
- Error message / stack trace (if any):

```
<Error message / Stack trace here>
```

**Comment by ronjouch** [comment] 2020-01-29 04:14
Yup, not supported for now. Closing as duplicate of https://github.com/jiahaog/nativefier/issues/504 .

**Closed by ronjouch** 2020-01-29 04:15 UTC
