### ISSUE TITLE
nativefier not work cookie

### ISSUE THREAD

**Issue by soltaneghalbha** [jiahaog/nativefier#1059] opened 2020-10-23 17:38 UTC
hello
i,am create app with nativefier for site, but cookie not work
me login account into site with app and close app
When I open the site, I have to login again
please help me
thx

**Comment by ronjouch** [comment] 2020-11-15 07:36
Hi @soltaneghalbha.

Sorry but I couldn't reproduce the issue, here the app produced by `nativefier 'https://news.ycombinator.com/'` with Nativefier 10.1.5 supports persistent cookies: I log into my HN account, I quit the app, I re-launch it, and am still logged in.

With that, closing. If you want help, please provide all the information requested by the [bug report template](https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Closed by ronjouch** 2020-11-15 07:36 UTC
Labels: question
