### ISSUE TITLE
Nativefied app inhibits screensaver / sleep mode

### ISSUE THREAD

**Issue by carriopablo** [jiahaog/nativefier#552] opened 2018-03-07 10:52 UTC
### Description

It seems that if if I leave the computer with the app opened the screensaver (or screen sleep modele) dosen't start

### Details

- Are you nativefying a *public* website? No, localhost.
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? Yes. Nothing
- Full nativefier command used to build your app: `nativefier --name "Sushiber" 'http://loclahost:8069/web'`
- Version of Nativefier (run `nativefier --version`): `v7.5.4`
- Version of node.js (run `node --version`): `v4.2.6`
- OS: `Ubuntu`

**Comment by ronjouch** [comment] 2018-03-17 13:39
@carriopablo I cannot reproduce your issue here under Linux. Can you precise the OS you are using and provide a scenario reproducible on a *public* website?

**Comment by ronjouch** [comment] 2018-04-17 13:52
Closing as issue wasn't reproducible and didn't get feedback. feel free to chime in and re-open the discussion anytime 🙂!

**Closed by ronjouch** 2018-04-17 13:52 UTC
Labels: cannot reproduce, need info
