### ISSUE TITLE
Icon disappear when move app

### ISSUE THREAD

**Issue by pando85** [jiahaog/nativefier#309] opened 2017-01-08 11:27 UTC
### Description
Icon disapper when move app path.

### Steps to Reproduce Issue
- Build app with icon
- move icon to other path

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.0.1`
- Version of Node.js (run `$ node --version`): `v7.3.0`
- OS: `4.4.39-1-MANJARO #1 SMP PREEMPT Thu Dec 15 21:29:27 UTC 2016 x86_64 GNU/Linux`
- Architecture `x64`

**Comment by ronjouch** [comment] 2017-04-08 00:33
Hi @pando85, thanks for the report. I cannot reproduce the issue, can you be more precise and/or try with a recent nativefier + electron? Here's what I tried:

1. Run `nativefier -e 1.6.6 --name "feedly" --icon "/opt/feedly.png" "https://feedly.com/i/latest"`
2. Run `./feedly-linux-x64/feedly` and verify icon is visible in the GNOME Shell alt-tab switcher; it is.
3. Run `mv ./feedly-linux-x64 ./foo && ./foo/feedly` and verify icon is visible in the GNOME Shell alt-tab switcher; it still is for me.

**Comment by ronjouch** [comment] 2017-04-21 01:34
Closing as issue wasn't reproducible and didn't get feedback. @pando85  feel free to chime in and re-open the discussion anytime 😃!

**Closed by ronjouch** 2017-04-21 01:34 UTC
Labels: bug, cannot reproduce
