### ISSUE TITLE
Cannot build nativefier Docker Image o Manjaro Linux

### ISSUE THREAD

**Issue by PhantomNimbi** [jiahaog/nativefier#1061] opened 2020-10-29 10:16 UTC
**Homework**

- [ ] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [x] I searched existing issues, open & closed. Yes, my bug is new.
- [ ] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Bug description**
Attempting to build nativefier docker image fails on Manjaro XFCE Linux

**Steps to reproduce**
`docker build -t local/nativefier .`

Give your ***full*** nativefier command and its logs, with the ***`--verbose` flag***, on a ***public*** site:

```
docker build -t local/nativefier .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/nimbi/Dockerfile: no such file or directory
```

**Expected behavior**

Successful build

**Actual behavior**

Failed build

**Debug info**

- Console logs of your `nativefier` build command, with `--verbose` flag
- If the bug happens at app run time, the in-app DevTools console logs (open it with F12)
- Error messages
- Screenshots
- Anything else relevant!

**Context**

 - Nativefier: latest
 - Node.js: 14.12.0
 - Npm: 6.14.7
 - OS: Manjaro XFCE 20.1.2
 - Is it a regression?
 - Additional context:

**Comment by ronjouch** [comment] 2020-11-15 07:53
@PhantomNimbi hi. Sorry but I couldn't reproduce your issue, I successfully built the Nativefier docker image under Arch, just now.

Feel free to come back with more debug info. Until then, closing.

**Closed by ronjouch** 2020-11-15 07:53 UTC
Labels: bug
