### ISSUE TITLE
Lazy reload and startup (without white screen when refreshing/starting)

### ISSUE THREAD

**Issue by Animeshz** [jiahaog/nativefier#981] opened 2020-05-26 14:00 UTC
**Problem statement**
As the title suggests. Feature request is for responsiveness i.e. when loading the pages preserving old page till the new one loads, and also when starting the application do not show white screen (till page has been loaded) which can be done as explained in [here](https://www.christianengvall.se/electron-white-screen-app-startup)

- [x] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md , no existing option fits my needs.
- [x] I searched existing open & closed issues. Yes, my issue is new.

**Suggested solution**
Completely add functionality for lazily refreshing/loading new page, while creating an option for configuring the lazy startup.

**Alternative solutions**
To add options for configuring both of the above behavior.

**Context**
 - Nativefier: 8.0.7
 - Node.js: 12.16.3
 - Npm: 6.14.4
 - OS: Windows 10 build 1909

**Comment by ronjouch** [comment] 2020-06-13 13:46
@Animeshz closing as duplicate of https://github.com/jiahaog/nativefier/issues/981 . I'm adding the link you mentioned at https://github.com/jiahaog/nativefier/issues/183#issuecomment-643626098 . Thanks!

**Closed by ronjouch** 2020-06-13 13:46 UTC
