### ISSUE TITLE
IBM Verse Mail: "Open in new window" button opens a blank window

### ISSUE THREAD

**Issue by kskafte** [jiahaog/nativefier#662] opened 2018-07-27 12:31 UTC
Mail: "Open in new window" button opens a blank window.

<img width="102" alt="image" src="https://user-images.githubusercontent.com/41789205/43320579-39b73eb0-91a9-11e8-9713-86d504de2648.png">

[ctrl] Click "Open with default browser" doesn't work either.

**Comment by ronjouch** [comment] 2018-07-27 12:42
Closing as duplicate of https://github.com/jiahaog/nativefier/issues/408

**Closed by ronjouch** 2018-07-27 12:42 UTC
